import { useEffect, useMemo, useState, type ReactNode } from "react";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { fetchAllPaginated } from "@/lib/fetchAllRows";
import { fetchAttendanceDayRange } from "@/hooks/hrms/useAttendanceDay";
import { splitOwnerStats } from "@/lib/ownerStatsExclusion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Tooltip as UiTooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, AlertCircle, ArrowDownRight, ArrowRight, ArrowUpRight, CircleDollarSign, Download, Info, Landmark, Minus, Users, Wallet } from "lucide-react";
import * as XLSX from "xlsx";
import { PageHeader } from "@/components/shared/PageHeader";
import { SectionHeader } from "@/components/hrms/primitives/SectionHeader";
import { MonthlyPayrollBreakdownDialog } from "@/components/hrms/MonthlyPayrollBreakdownDialog";
import { DetailDialog, HoverPanel, Insight, type DetailSpec, type HoverLine } from "@/components/hrms/reports/ReportInsight";

const COLORS = ["hsl(var(--primary))", "hsl(var(--success))", "hsl(var(--warning))", "hsl(var(--destructive))", "hsl(var(--info))", "hsl(var(--muted-foreground))"];
const PAID_LEAVE_STATUSES = new Set(["approved", "manager_approved"]);
const PENDING_LEAVE_STATUSES = new Set(["requested", "pending"]);
const inr = (n: number) => `₹${Math.round(n || 0).toLocaleString("en-IN")}`;
const pct = (n: number) => `${Number.isFinite(n) ? n.toFixed(1) : "0.0"}%`;
const monthLabel = (iso: string) => new Date(`${iso.slice(0, 7)}-01T00:00:00`).toLocaleDateString("en-IN", { month: "short", year: "2-digit" });
const currentMonth = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`; };
const lastDayOfMonth = (month: string) => { const [year, number] = month.split("-").map(Number); return `${month}-${String(new Date(year, number, 0).getDate()).padStart(2, "0")}`; };
const shiftMonth = (month: string, offset: number) => { const [year, number] = month.split("-").map(Number); const date = new Date(year, number - 1 + offset, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; };
const signedPct = (value: number | null) => value == null ? "No comparison" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}% vs previous`;

type PayrollMonth = { key: string; month: string; gross: number; net: number; deductions: number; tds: number; pf: number; esi: number; pt: number; er: number; count: number; paidIds: Set<string>; withRegister: number; esiCovered: number };

function MetricCard({ label, value, helper, icon: Icon, tone = "primary", hover, onOpen }: { label: string; value: ReactNode; helper: ReactNode; icon: typeof Users; tone?: "primary" | "success" | "warning" | "destructive"; hover?: ReactNode; onOpen?: () => void }) {
  const tones = { primary: "bg-primary/10 text-primary", success: "bg-success/10 text-success", warning: "bg-warning/10 text-warning", destructive: "bg-destructive/10 text-destructive" };
  return <Insight hover={hover} onOpen={onOpen} className="h-full"><Card className="h-full min-w-0 overflow-hidden transition-shadow hover:shadow-md hover:ring-1 hover:ring-primary/30"><CardContent className="flex h-full min-h-[9rem] flex-col p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><p className="max-w-[75%] text-[11px] font-semibold uppercase leading-snug text-muted-foreground">{label}</p><span className={`inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${tones[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-4 font-semibold tabular-nums text-foreground [font-family:'Space_Grotesk_Variable',sans-serif] text-[clamp(1.5rem,2.2vw,2rem)] leading-none">{value}</p><div className="mt-auto border-t border-border/60 pt-3 text-[11px] leading-snug text-muted-foreground">{helper}</div></CardContent></Card></Insight>;
}

function Delta({ value, invert = false }: { value: number | null; invert?: boolean }) {
  if (value == null || Math.abs(value) < 0.05) return <span className="inline-flex items-center gap-1"><Minus className="h-3 w-3" />{value == null ? "No comparison" : "No change"}</span>;
  const good = invert ? value < 0 : value > 0;
  const Icon = value > 0 ? ArrowUpRight : ArrowDownRight;
  return <span className={`inline-flex items-center gap-1 font-medium ${good ? "text-success" : "text-destructive"}`}><Icon className="h-3 w-3" />{signedPct(value)}</span>;
}

function InsightItem({ label, value, note, tone = "default" }: { label: string; value: ReactNode; note?: string; tone?: "default" | "warning" | "danger" }) {
  return <div className="min-w-0"><p className="text-[10px] font-semibold uppercase text-muted-foreground">{label}</p><p className={`mt-1 text-sm font-semibold tabular-nums ${tone === "danger" ? "text-destructive" : tone === "warning" ? "text-warning" : "text-foreground"}`}>{value}</p>{note && <p className="mt-0.5 text-[11px] leading-snug text-muted-foreground">{note}</p>}</div>;
}

function RankedBar({ label, value, max, suffix, detail }: { label: string; value: number; max: number; suffix?: string; detail?: string }) {
  return <div className="space-y-1.5"><div className="flex items-center justify-between gap-3 text-xs"><span className="min-w-0 truncate font-medium text-foreground">{label}</span><span className="shrink-0 tabular-nums text-muted-foreground">{value.toLocaleString("en-IN")}{suffix}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${max ? Math.max(2, value / max * 100) : 0}%` }} /></div>{detail && <p className="text-[10px] text-muted-foreground">{detail}</p>}</div>;
}

export default function ReportsPage() {
  const [periodMode, setPeriodMode] = useState<"month" | "range">("month");
  const [monthFrom, setMonthFrom] = useState(currentMonth);
  const [monthTo, setMonthTo] = useState(currentMonth);
  const [defaultsApplied, setDefaultsApplied] = useState(false);
  const [drillMonth, setDrillMonth] = useState<string | null>(null);
  const [detail, setDetail] = useState<DetailSpec | null>(null);
  const dateFrom = `${monthFrom}-01`;
  const dateTo = lastDayOfMonth(periodMode === "month" ? monthFrom : monthTo);

  const prevWindow = useMemo(() => {
    const [fy, fm] = monthFrom.split("-").map(Number);
    const [ty, tm] = (periodMode === "month" ? monthFrom : monthTo).split("-").map(Number);
    const count = Math.max(1, (ty - fy) * 12 + tm - fm + 1);
    const toMonth = shiftMonth(monthFrom, -1);
    const fromMonth = shiftMonth(monthFrom, -count);
    return { from: `${fromMonth}-01`, to: lastDayOfMonth(toMonth) };
  }, [monthFrom, monthTo, periodMode]);

  const { data: latestProcessedMonth } = useQuery({ queryKey: ["rpt_latest_processed_month"], queryFn: async () => { const { data } = await supabase.from("hr_payslips_v").select("period_month").order("period_month", { ascending: false }).limit(1); return (data?.[0]?.period_month as string | undefined)?.slice(0, 7) ?? null; }, staleTime: 60_000 });
  useEffect(() => { if (defaultsApplied || !latestProcessedMonth) return; setDefaultsApplied(true); setPeriodMode("month"); setMonthFrom(latestProcessedMonth); setMonthTo(latestProcessedMonth); }, [defaultsApplied, latestProcessedMonth]);

  const { data: allEmployees = [] } = useQuery({ queryKey: ["rpt_employees"], queryFn: () => fetchAllPaginated<any>(() => supabase.from("hr_employees").select("id, badge_id, first_name, last_name, is_active, total_salary, resignation_date, last_working_day")) });
  const { kept: employees, excludedIds: excludedEmployeeIds } = useMemo(() => splitOwnerStats(allEmployees), [allEmployees]);
  const employeeIds = useMemo(() => employees.map((employee: any) => employee.id), [employees]);
  const employeeKey = employeeIds.join(",");
  const { data: workInfos = [] } = useQuery({ queryKey: ["rpt_work_infos"], queryFn: () => fetchAllPaginated<any>(() => supabase.from("hr_employee_work_info").select("employee_id, employee_type, department_id, joining_date, job_position_id")) });
  const { data: departments = [] } = useQuery({ queryKey: ["rpt_departments"], queryFn: async () => { const { data } = await supabase.from("departments").select("id, name"); return data || []; } });
  const { data: leaveRequests = [] } = useQuery({ queryKey: ["rpt_leaves"], queryFn: () => fetchAllPaginated<any>(() => supabase.from("hr_leave_requests").select("id, employee_id, status, total_days, leave_type_id, start_date, end_date, created_at")) });
  const { data: leaveTypes = [] } = useQuery({ queryKey: ["rpt_leave_types"], queryFn: async () => { const { data } = await supabase.from("hr_leave_types").select("id, name"); return data || []; } });

  const payrollSelect = "employee_id, period_month, gross, regular_gross, net, total_deductions, tds_amount, pf_amount, esi_amount, professional_tax, employer_contrib, employer_pf, employer_esi, register_source, basic, hra, special_allowance, overtime, performance_incentive, one_time_payments, one_time_recovery, loan_emi, advance_salary, working_days";
  const { data: payslips = [] } = useQuery({ queryKey: ["rpt_payslips", dateFrom, dateTo], placeholderData: keepPreviousData, queryFn: () => fetchAllPaginated<any>(() => (supabase as any).from("hr_payslips_v").select(payrollSelect).gte("period_month", dateFrom).lte("period_month", dateTo)) });
  const { data: previousPayslips = [] } = useQuery({ queryKey: ["rpt_payslips_previous", prevWindow.from, prevWindow.to], placeholderData: keepPreviousData, queryFn: () => fetchAllPaginated<any>(() => (supabase as any).from("hr_payslips_v").select(payrollSelect).gte("period_month", prevWindow.from).lte("period_month", prevWindow.to)) });
  const { data: attendance = [] } = useQuery({ queryKey: ["rpt_availability", dateFrom, dateTo, employeeKey], enabled: employeeIds.length > 0, placeholderData: keepPreviousData, queryFn: async () => (await fetchAttendanceDayRange(employeeIds, dateFrom, dateTo)).filter(day => day.evidence_backed) });
  const { data: prevAttendance = [] } = useQuery({ queryKey: ["rpt_availability_previous", prevWindow.from, prevWindow.to, employeeKey], enabled: employeeIds.length > 0, placeholderData: keepPreviousData, queryFn: async () => (await fetchAttendanceDayRange(employeeIds, prevWindow.from, prevWindow.to)).filter(day => day.evidence_backed) });

  const empById = useMemo(() => new Map(employees.map((e: any) => [e.id, e])), [employees]);
  const wiByEmp = useMemo(() => new Map(workInfos.map((w: any) => [w.employee_id, w])), [workInfos]);
  const deptById = useMemo(() => new Map(departments.map((d: any) => [d.id, d.name])), [departments]);
  const empName = (id: string) => { const employee: any = empById.get(id); return employee ? `${employee.first_name || ""} ${employee.last_name || ""}`.trim() || employee.badge_id || id : id; };
  const deptOf = (id: string) => deptById.get(wiByEmp.get(id)?.department_id) || "Unassigned";
  const exitDateOf = (employee: any) => employee.last_working_day || employee.resignation_date || null;
  const inRange = (date?: string | null) => !!date && date.slice(0, 10) >= dateFrom && date.slice(0, 10) <= dateTo;

  const filteredPayroll = useMemo(() => payslips.filter((p: any) => !excludedEmployeeIds.has(p.employee_id)), [payslips, excludedEmployeeIds]);
  const filteredPreviousPayroll = useMemo(() => previousPayslips.filter((p: any) => !excludedEmployeeIds.has(p.employee_id)), [previousPayslips, excludedEmployeeIds]);
  const aggregatePayroll = (rows: any[]): PayrollMonth[] => {
    const months: Record<string, PayrollMonth> = {};
    rows.forEach((p: any) => { const key = String(p.period_month).slice(0, 7); const row = months[key] || (months[key] = { key, month: monthLabel(key), gross: 0, net: 0, deductions: 0, tds: 0, pf: 0, esi: 0, pt: 0, er: 0, count: 0, paidIds: new Set(), withRegister: 0, esiCovered: 0 }); row.gross += Number(p.gross || 0); row.net += Number(p.net || 0); row.deductions += Math.abs(Number(p.total_deductions || 0)); row.tds += Math.abs(Number(p.tds_amount || 0)); row.pf += Math.abs(Number(p.pf_amount || 0)); row.esi += Math.abs(Number(p.esi_amount || 0)); row.pt += Math.abs(Number(p.professional_tax || 0)); row.er += Number(p.employer_contrib || 0); row.count++; row.paidIds.add(p.employee_id); if (p.register_source) row.withRegister++; if (Math.abs(Number(p.esi_amount || 0)) > 0) row.esiCovered++; });
    return Object.values(months).sort((a, b) => a.key.localeCompare(b.key));
  };
  const payrollMonths = useMemo(() => aggregatePayroll(filteredPayroll), [filteredPayroll]);
  const previousPayrollMonths = useMemo(() => aggregatePayroll(filteredPreviousPayroll), [filteredPreviousPayroll]);
  const sumPayroll = (rows: PayrollMonth[]) => rows.reduce((sum, row) => ({ gross: sum.gross + row.gross, net: sum.net + row.net, deductions: sum.deductions + row.deductions, er: sum.er + row.er, pf: sum.pf + row.pf, esi: sum.esi + row.esi, pt: sum.pt + row.pt, tds: sum.tds + row.tds }), { gross: 0, net: 0, deductions: 0, er: 0, pf: 0, esi: 0, pt: 0, tds: 0 });
  const payroll = useMemo(() => sumPayroll(payrollMonths), [payrollMonths]);
  const previousPayroll = useMemo(() => sumPayroll(previousPayrollMonths), [previousPayrollMonths]);
  const employerCost = payroll.gross + payroll.er;
  const previousEmployerCost = previousPayroll.gross + previousPayroll.er;
  const payrollDelta = previousEmployerCost ? (employerCost - previousEmployerCost) / previousEmployerCost * 100 : null;
  const paidEmployees = useMemo(() => new Set(filteredPayroll.map((row: any) => row.employee_id)).size, [filteredPayroll]);
  const costPerPaidEmployee = paidEmployees ? employerCost / paidEmployees : 0;
  const registerRows = payrollMonths.reduce((sum, row) => sum + row.withRegister, 0);
  const registerCoverage = filteredPayroll.length ? registerRows / filteredPayroll.length * 100 : 0;

  const openingHeadcount = useMemo(() => employees.filter((e: any) => { const joined = wiByEmp.get(e.id)?.joining_date; const exit = exitDateOf(e); return joined && joined < dateFrom && (!exit || exit >= dateFrom); }).length, [employees, wiByEmp, dateFrom]);
  const joinsInRange = useMemo(() => workInfos.filter((w: any) => empById.has(w.employee_id) && inRange(w.joining_date)), [workInfos, empById, dateFrom, dateTo]);
  const exitsInRange = useMemo(() => employees.filter((e: any) => inRange(exitDateOf(e))), [employees, dateFrom, dateTo]);
  const closingHeadcount = openingHeadcount + joinsInRange.length - exitsInRange.length;
  const activeCount = employees.filter((employee: any) => employee.is_active).length;
  const averageHeadcount = Math.max(0, (openingHeadcount + closingHeadcount) / 2);
  const monthSpan = Math.max(1, ((Number((periodMode === "month" ? monthFrom : monthTo).slice(0, 4)) - Number(monthFrom.slice(0, 4))) * 12) + Number((periodMode === "month" ? monthFrom : monthTo).slice(5, 7)) - Number(monthFrom.slice(5, 7)) + 1);
  const attritionRate = averageHeadcount ? exitsInRange.length / averageHeadcount * (12 / monthSpan) * 100 : 0;

  const availability = (rows: any[]) => { let present = 0, half = 0, absent = 0, incomplete = 0, minutes = 0, worked = 0; rows.forEach((row: any) => { if (row.status === "present") present++; else if (row.status === "half_day") half++; else if (row.status === "absent") absent++; else if (row.status === "incomplete") incomplete++; const value = Number(row.worked_minutes || 0); if (value > 0) { minutes += value; worked++; } }); const marked = present + half + absent + incomplete; const equivalentWorked = present + half * 0.5 + incomplete * 0.5; return { marked, rate: marked ? equivalentWorked / marked * 100 : 0, lost: marked - equivalentWorked, averageHours: worked ? minutes / worked / 60 : 0 }; };
  const availabilityNow = useMemo(() => availability(attendance), [attendance]);
  const availabilityPrevious = useMemo(() => availability(prevAttendance), [prevAttendance]);
  const availabilityDelta = availabilityPrevious.marked ? availabilityNow.rate - availabilityPrevious.rate : null;

  const selectedLeaves = useMemo(() => leaveRequests.filter((leave: any) => {
    if (excludedEmployeeIds.has(leave.employee_id)) return false;
    const start = String(leave.start_date || leave.created_at || "").slice(0, 10);
    const end = String(leave.end_date || leave.start_date || leave.created_at || "").slice(0, 10);
    return start <= dateTo && end >= dateFrom;
  }), [leaveRequests, excludedEmployeeIds, dateFrom, dateTo]);
  const approvedLeaves = useMemo(() => selectedLeaves.filter((leave: any) => PAID_LEAVE_STATUSES.has(String(leave.status || "").toLowerCase())), [selectedLeaves]);
  const pendingLeaves = useMemo(() => selectedLeaves.filter((leave: any) => PENDING_LEAVE_STATUSES.has(String(leave.status || "").toLowerCase()) && String(leave.status || "").toLowerCase() !== "approved"), [selectedLeaves]);
  const approvedLeaveDays = approvedLeaves.reduce((sum: number, leave: any) => sum + Number(leave.total_days || 0), 0);
  const leaveDaysPerEmployee = activeCount ? approvedLeaveDays / activeCount : 0;
  const leaveTypeName = (id: string) => leaveTypes.find((type: any) => type.id === id)?.name || "Unassigned";
  const leaveByType = useMemo(() => { const map: Record<string, number> = {}; approvedLeaves.forEach((leave: any) => { const label = leaveTypeName(leave.leave_type_id); map[label] = (map[label] || 0) + Number(leave.total_days || 0); }); return Object.entries(map).map(([name, days]) => ({ name, days })).sort((a, b) => b.days - a.days); }, [approvedLeaves, leaveTypes]);
  const leaveByDepartment = useMemo(() => { const map: Record<string, number> = {}; approvedLeaves.forEach((leave: any) => { const name = deptOf(leave.employee_id); map[name] = (map[name] || 0) + Number(leave.total_days || 0); }); return Object.entries(map).map(([name, days]) => ({ name, days })).sort((a, b) => b.days - a.days); }, [approvedLeaves, wiByEmp, deptById]);

  const departmentInsights = useMemo(() => { const map: Record<string, { name: string; active: number; gross: number; paidIds: Set<string> }> = {}; employees.filter((e: any) => e.is_active).forEach((e: any) => { const name = deptOf(e.id); const row = map[name] || (map[name] = { name, active: 0, gross: 0, paidIds: new Set() }); row.active++; }); filteredPayroll.forEach((p: any) => { const name = deptOf(p.employee_id); const row = map[name] || (map[name] = { name, active: 0, gross: 0, paidIds: new Set() }); row.gross += Number(p.gross || 0); row.paidIds.add(p.employee_id); }); return Object.values(map).map(row => ({ ...row, paid: row.paidIds.size, costPerPaid: row.paidIds.size ? row.gross / row.paidIds.size : 0, headcountShare: activeCount ? row.active / activeCount * 100 : 0, payrollShare: payroll.gross ? row.gross / payroll.gross * 100 : 0 })).sort((a, b) => b.gross - a.gross); }, [employees, filteredPayroll, activeCount, payroll.gross, wiByEmp, deptById]);
  const employeeTypes = useMemo(() => { const map: Record<string, number> = {}; workInfos.forEach((info: any) => { if (!empById.get(info.employee_id)?.is_active) return; const name = info.employee_type || "Unspecified"; map[name] = (map[name] || 0) + 1; }); return Object.entries(map).map(([name, count]) => ({ name, count, share: activeCount ? count / activeCount * 100 : 0 })).sort((a, b) => b.count - a.count); }, [workInfos, empById, activeCount]);
  const missingJoiningDates = employees.filter((employee: any) => !wiByEmp.get(employee.id)?.joining_date).length;
  const unmappedDepartments = employees.filter((employee: any) => employee.is_active && !wiByEmp.get(employee.id)?.department_id).length;
  const maxDepartmentGross = Math.max(0, ...departmentInsights.map(row => row.gross));
  const maxLeaveDays = Math.max(0, ...leaveByDepartment.map(row => row.days));

  const reportLabel = periodMode === "month" ? new Date(`${monthFrom}-01T00:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" }) : `${monthLabel(monthFrom)} – ${monthLabel(monthTo)}`;
  const payrollChart = payrollMonths.map(row => ({ ...row, employerCost: row.gross + row.er }));

  // ---------- Deeper analytics ----------
  const n = (v: any) => Math.abs(Number(v || 0));
  const money = { numeric: true, format: inr };
  const byEmployee = useMemo(() => { const map = new Map<string, any>(); filteredPayroll.forEach((p: any) => { const r = map.get(p.employee_id) || { id: p.employee_id, months: 0, gross: 0, er: 0, net: 0, ded: 0, pf: 0, esi: 0, pt: 0, tds: 0, basic: 0, hra: 0, special: 0, variable: 0, recovery: 0, days: 0 }; r.months++; r.gross += Number(p.gross || 0); r.er += Number(p.employer_contrib || 0); r.net += Number(p.net || 0); r.ded += n(p.total_deductions); r.pf += n(p.pf_amount); r.esi += n(p.esi_amount); r.pt += n(p.professional_tax); r.tds += n(p.tds_amount); r.basic += n(p.basic); r.hra += n(p.hra); r.special += n(p.special_allowance); r.variable += n(p.overtime) + n(p.performance_incentive) + n(p.one_time_payments); r.recovery += n(p.loan_emi) + n(p.one_time_recovery); r.days += Number(p.working_days || 0); map.set(p.employee_id, r); }); return [...map.values()].map(r => ({ ...r, cost: r.gross + r.er })).sort((a, b) => b.cost - a.cost); }, [filteredPayroll]);
  const empRow = (r: any) => [empName(r.id), deptOf(r.id)];
  const variablePay = byEmployee.reduce((s, r) => s + r.variable, 0);
  const recoveries = byEmployee.reduce((s, r) => s + r.recovery, 0);
  const variableShare = payroll.gross ? variablePay / payroll.gross * 100 : 0;
  const topCount = Math.max(1, Math.ceil(byEmployee.length * 0.1));
  const topShare = payroll.gross ? byEmployee.slice().sort((a, b) => b.gross - a.gross).slice(0, topCount).reduce((s, r) => s + r.gross, 0) / payroll.gross * 100 : 0;
  const monthlyGrossList = useMemo(() => filteredPayroll.map((p: any) => Number(p.gross || 0)).filter(v => v > 0).sort((a, b) => a - b), [filteredPayroll]);
  const medianGross = monthlyGrossList.length ? monthlyGrossList[Math.floor(monthlyGrossList.length / 2)] : 0;
  const BANDS: [string, number, number][] = [["Under ₹15K", 0, 15000], ["₹15K – 25K", 15000, 25000], ["₹25K – 40K", 25000, 40000], ["₹40K – 60K", 40000, 60000], ["₹60K+", 60000, Infinity]];
  const salaryBands = useMemo(() => BANDS.map(([name, lo, hi]) => { const rows = filteredPayroll.filter((p: any) => { const g = Number(p.gross || 0); return g > 0 && g >= lo && g < hi; }); return { name, count: rows.length, gross: rows.reduce((s: number, p: any) => s + Number(p.gross || 0), 0), rows }; }), [filteredPayroll]);
  const monthsBetween = (a: string, b: string) => (new Date(b).getTime() - new Date(a).getTime()) / (1000 * 60 * 60 * 24 * 30.44);
  const activeAtEnd = useMemo(() => employees.filter((e: any) => { const j = wiByEmp.get(e.id)?.joining_date; const x = exitDateOf(e); return j && j <= dateTo && (!x || x > dateTo); }), [employees, wiByEmp, dateTo]);
  const TENURE: [string, number, number][] = [["< 3 months", 0, 3], ["3 – 6 months", 3, 6], ["6 – 12 months", 6, 12], ["1 – 2 years", 12, 24], ["2+ years", 24, Infinity]];
  const tenureBands = useMemo(() => TENURE.map(([name, lo, hi]) => { const people = activeAtEnd.filter((e: any) => { const m = monthsBetween(wiByEmp.get(e.id).joining_date, dateTo); return m >= lo && m < hi; }); return { name, people, count: people.length }; }), [activeAtEnd, dateTo]);
  const avgTenure = activeAtEnd.length ? activeAtEnd.reduce((s: number, e: any) => s + monthsBetween(wiByEmp.get(e.id).joining_date, dateTo), 0) / activeAtEnd.length : 0;
  const exitTenures = exitsInRange.map((e: any) => { const j = wiByEmp.get(e.id)?.joining_date; return { e, months: j ? monthsBetween(j, exitDateOf(e)) : null }; });
  const earlyExits = exitTenures.filter(x => x.months != null && x.months < 6).length;
  const availabilityByEmp = useMemo(() => { const map = new Map<string, any[]>(); attendance.forEach((d: any) => { const l = map.get(d.employee_id) || []; l.push(d); map.set(d.employee_id, l); }); return [...map.entries()].map(([id, rows]) => { let p = 0, h = 0, a = 0, i = 0, mins = 0; rows.forEach((d: any) => { if (d.status === "present") p++; else if (d.status === "half_day") h++; else if (d.status === "absent") a++; else if (d.status === "incomplete") i++; mins += Number(d.worked_minutes || 0); }); const marked = p + h + a + i; return { id, p, h, a, i, marked, rate: marked ? (p + (h + i) * 0.5) / marked * 100 : 0, hours: (p + h + i) ? mins / (p + h + i) / 60 : 0 }; }).sort((x, y) => x.rate - y.rate); }, [attendance]);
  const lowAvailability = availabilityByEmp.filter(r => r.marked >= 3 && r.rate < 85);
  const leaveByEmp = useMemo(() => { const map = new Map<string, { id: string; days: number; count: number; types: Record<string, number> }>(); approvedLeaves.forEach((l: any) => { const r = map.get(l.employee_id) || { id: l.employee_id, days: 0, count: 0, types: {} }; const d = Number(l.total_days || 0); r.days += d; r.count++; const t = leaveTypeName(l.leave_type_id); r.types[t] = (r.types[t] || 0) + d; map.set(l.employee_id, r); }); return [...map.values()].sort((a, b) => b.days - a.days); }, [approvedLeaves, leaveTypes]);
  const lopDays = leaveByType.filter(t => /loss|lop|unpaid/i.test(t.name)).reduce((s, t) => s + t.days, 0);
  const lopShare = approvedLeaveDays ? lopDays / approvedLeaveDays * 100 : 0;
  const joinerCost = byEmployee.filter(r => joinsInRange.some((j: any) => j.employee_id === r.id)).reduce((s, r) => s + r.cost, 0);
  const exitCost = byEmployee.filter(r => exitsInRange.some((e: any) => e.id === r.id)).reduce((s, r) => s + r.cost, 0);
  const prevByEmp = useMemo(() => { const m = new Map<string, number>(); filteredPreviousPayroll.forEach((p: any) => m.set(p.employee_id, (m.get(p.employee_id) || 0) + Number(p.gross || 0) + Number(p.employer_contrib || 0))); return m; }, [filteredPreviousPayroll]);
  const costMovers = byEmployee.filter(r => prevByEmp.has(r.id)).map(r => ({ ...r, prev: prevByEmp.get(r.id)!, change: r.cost - prevByEmp.get(r.id)! })).sort((a, b) => Math.abs(b.change) - Math.abs(a.change));

  const open = setDetail;
  const openPayrollEmployees = (title: string, list: any[], description?: string) => open({ title, description: description || reportLabel, stats: [{ label: "Employees", value: list.length }, { label: "Gross", value: inr(list.reduce((s, r) => s + r.gross, 0)) }, { label: "Employer cost", value: inr(list.reduce((s, r) => s + r.cost, 0)) }, { label: "Net paid", value: inr(list.reduce((s, r) => s + r.net, 0)) }], columns: [{ label: "Employee" }, { label: "Department" }, { label: "Gross", ...money }, { label: "Employer contrib.", ...money }, { label: "Employer cost", ...money }, { label: "Deductions", ...money }, { label: "Net paid", ...money }], rows: list.map(r => [...empRow(r), r.gross, r.er, r.cost, r.ded, r.net]) });
  const openPeople = (title: string, people: any[], extraLabel?: string, extra?: (e: any) => string | number) => open({ title, description: reportLabel, stats: [{ label: "People", value: people.length }], columns: [{ label: "Employee" }, { label: "Badge" }, { label: "Department" }, { label: "Type" }, { label: "Joined" }, { label: "Exit" }, ...(extraLabel ? [{ label: extraLabel, numeric: true, total: false }] : [])], rows: people.map((e: any) => [empName(e.id), e.badge_id || "—", deptOf(e.id), wiByEmp.get(e.id)?.employee_type || "—", wiByEmp.get(e.id)?.joining_date || "—", exitDateOf(e) || "—", ...(extra ? [extra(e)] : [])]) });
  const openStatutory = () => open({ title: "Statutory and tax by employee", description: reportLabel, stats: [{ label: "PF (EE)", value: inr(payroll.pf) }, { label: "ESI (EE)", value: inr(payroll.esi) }, { label: "Professional tax", value: inr(payroll.pt) }, { label: "TDS", value: inr(payroll.tds) }, { label: "Employer contrib.", value: inr(payroll.er) }, { label: "Register coverage", value: `${registerCoverage.toFixed(0)}%`, tone: registerCoverage < 100 ? "warning" : "success" }], columns: [{ label: "Employee" }, { label: "Department" }, { label: "PF", ...money }, { label: "ESI", ...money }, { label: "PT", ...money }, { label: "TDS", ...money }, { label: "Employer contrib.", ...money }], rows: byEmployee.map(r => [...empRow(r), r.pf, r.esi, r.pt, r.tds, r.er]) });
  const openAvailability = (list = availabilityByEmp, title = "Availability by employee") => open({ title, description: `${reportLabel} · evidence-backed days only`, stats: [{ label: "Availability", value: pct(availabilityNow.rate) }, { label: "Marked days", value: availabilityNow.marked }, { label: "Days lost", value: availabilityNow.lost.toLocaleString("en-IN") }, { label: "Below 85%", value: lowAvailability.length, tone: lowAvailability.length ? "warning" : "success" }], columns: [{ label: "Employee" }, { label: "Department" }, { label: "Marked", numeric: true }, { label: "Present", numeric: true }, { label: "Half / incomplete", numeric: true }, { label: "Absent", numeric: true }, { label: "Availability %", numeric: true, total: false, format: pct }, { label: "Avg hours", numeric: true, total: false, format: v => `${v.toFixed(1)} h` }], rows: list.map(r => [...empRow(r), r.marked, r.p, r.h + r.i, r.a, r.rate, r.hours]) });
  const openLeave = (list = leaveByEmp, title = "Approved leave by employee") => { const types = leaveByType.map(t => t.name); open({ title, description: reportLabel, stats: [{ label: "Approved days", value: approvedLeaveDays.toLocaleString("en-IN") }, { label: "Requests", value: approvedLeaves.length }, { label: "Pending", value: pendingLeaves.length, tone: pendingLeaves.length ? "warning" : "default" }, { label: "Loss of pay share", value: pct(lopShare), tone: lopShare > 25 ? "danger" : "default" }], columns: [{ label: "Employee" }, { label: "Department" }, { label: "Requests", numeric: true }, { label: "Days", numeric: true }, ...types.map(t => ({ label: t, numeric: true }))], rows: list.map(r => [...empRow(r), r.count, r.days, ...types.map(t => r.types[t] || 0)]) }); };
  const openPending = () => open({ title: "Pending leave decisions", description: reportLabel, columns: [{ label: "Employee" }, { label: "Department" }, { label: "Type" }, { label: "From" }, { label: "To" }, { label: "Days", numeric: true }, { label: "Waiting (days)", numeric: true, total: false }], rows: pendingLeaves.map((l: any) => [empName(l.employee_id), deptOf(l.employee_id), leaveTypeName(l.leave_type_id), l.start_date || "—", l.end_date || "—", Number(l.total_days || 0), Math.max(0, Math.round((Date.now() - new Date(l.created_at).getTime()) / 86400000))]) });
  const openDepartment = (name: string) => { const list = byEmployee.filter(r => deptOf(r.id) === name); const people = employees.filter((e: any) => e.is_active && deptOf(e.id) === name); const lv = leaveByEmp.filter(r => deptOf(r.id) === name).reduce((s, r) => s + r.days, 0); open({ title: `${name} department`, description: reportLabel, stats: [{ label: "Active", value: people.length }, { label: "Paid", value: list.length }, { label: "Employer cost", value: inr(list.reduce((s, r) => s + r.cost, 0)) }, { label: "Avg cost / paid", value: inr(list.length ? list.reduce((s, r) => s + r.cost, 0) / list.length : 0) }, { label: "Leave days", value: lv }], columns: [{ label: "Employee" }, { label: "Gross", ...money }, { label: "Employer cost", ...money }, { label: "Variable pay", ...money }, { label: "Net paid", ...money }], rows: list.map(r => [empName(r.id), r.gross, r.cost, r.variable, r.net]) }); };
  const openComposition = () => open({ title: "Pay composition by employee", description: `${reportLabel} · variable = overtime + incentives + one-time payments`, stats: [{ label: "Basic", value: inr(byEmployee.reduce((s, r) => s + r.basic, 0)) }, { label: "HRA", value: inr(byEmployee.reduce((s, r) => s + r.hra, 0)) }, { label: "Special allowance", value: inr(byEmployee.reduce((s, r) => s + r.special, 0)) }, { label: "Variable", value: inr(variablePay) }, { label: "Variable share", value: pct(variableShare) }], columns: [{ label: "Employee" }, { label: "Department" }, { label: "Basic", ...money }, { label: "HRA", ...money }, { label: "Special", ...money }, { label: "Variable", ...money }, { label: "Gross", ...money }], rows: byEmployee.map(r => [...empRow(r), r.basic, r.hra, r.special, r.variable, r.gross]) });
  const openRecoveries = () => open({ title: "Loan and one-time recoveries", description: reportLabel, columns: [{ label: "Employee" }, { label: "Department" }, { label: "Recovered", ...money }, { label: "Net paid", ...money }], rows: byEmployee.filter(r => r.recovery > 0).sort((a, b) => b.recovery - a.recovery).map(r => [...empRow(r), r.recovery, r.net]) });
  const openMovers = () => open({ title: "Biggest cost changes vs previous period", description: "Same employees paid in both periods", columns: [{ label: "Employee" }, { label: "Department" }, { label: "Previous", ...money }, { label: "Current", ...money }, { label: "Change", ...money }], rows: costMovers.map(r => [...empRow(r), r.prev, r.cost, r.change]) });
  const openBand = (band: typeof salaryBands[number]) => open({ title: `Monthly gross ${band.name}`, description: reportLabel, columns: [{ label: "Employee" }, { label: "Department" }, { label: "Month" }, { label: "Gross", ...money }, { label: "Net", ...money }], rows: band.rows.map((p: any) => [empName(p.employee_id), deptOf(p.employee_id), String(p.period_month).slice(0, 7), Number(p.gross || 0), Number(p.net || 0)]) });
  const hp = (title: string, lines: HoverLine[]) => <HoverPanel title={title} lines={lines} />;

  const handleExport = (type: string) => {
    let rows: any[] = []; let name = "Report";
    if (type === "employees") { name = "Employees"; rows = employees.map((e: any) => ({ "Badge ID": e.badge_id, Name: empName(e.id), Department: deptOf(e.id), "Employee Type": wiByEmp.get(e.id)?.employee_type || "", "Joining Date": wiByEmp.get(e.id)?.joining_date || "", Active: e.is_active ? "Yes" : "No", "Exit Date": exitDateOf(e) || "", CTC: Number(e.total_salary || 0) })); }
    if (type === "leaves") { name = "Leaves"; rows = selectedLeaves.map((l: any) => ({ Employee: empName(l.employee_id), Department: deptOf(l.employee_id), Type: leaveTypeName(l.leave_type_id), Status: l.status, Days: Number(l.total_days || 0), "Start Date": l.start_date, "End Date": l.end_date })); }
    if (type === "payroll_monthly") { name = "Payroll Monthly"; rows = payrollMonths.map(row => ({ Month: row.month, "Paid Employees": row.paidIds.size, "Gross Payroll": row.gross, "Employer Contribution": row.er, "Employer Payroll Cost": row.gross + row.er, Deductions: row.deductions, "Net Paid": row.net, TDS: row.tds, PF: row.pf, ESI: row.esi, PT: row.pt })); }
    if (type === "payroll_detail") { name = "Payslips"; rows = filteredPayroll.map((p: any) => ({ Month: String(p.period_month).slice(0, 7), "Badge ID": empById.get(p.employee_id)?.badge_id || "", Employee: empName(p.employee_id), Department: deptOf(p.employee_id), "Gross Payroll": Number(p.gross || 0), "Employer Contribution": Number(p.employer_contrib || 0), "Employer Payroll Cost": Number(p.gross || 0) + Number(p.employer_contrib || 0), Deductions: Math.abs(Number(p.total_deductions || 0)), "Net Paid": Number(p.net || 0), TDS: Math.abs(Number(p.tds_amount || 0)), PF: Math.abs(Number(p.pf_amount || 0)), ESI: Math.abs(Number(p.esi_amount || 0)), PT: Math.abs(Number(p.professional_tax || 0)) })); }
    if (type === "attendance") { name = "Availability"; rows = attendance.map((a: any) => ({ Date: a.date, "Badge ID": empById.get(a.employee_id)?.badge_id || "", Employee: empName(a.employee_id), Department: deptOf(a.employee_id), Status: a.status, "Worked Minutes": Number(a.worked_minutes || 0) })); }
    if (!rows.length) rows = [{ Note: "No data in the selected period" }];
    const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), name); XLSX.writeFile(book, `${name.toLowerCase().replace(/\s+/g, "_")}_${periodMode === "month" ? monthFrom : `${monthFrom}_to_${monthTo}`}.xlsx`);
  };

  const noData = (reason: string) => <div className="py-10 text-center"><p className="text-sm font-medium text-foreground">No data available</p><p className="mt-1 text-xs text-muted-foreground">{reason}</p></div>;

  return <TooltipProvider><div className="page-mount mx-auto w-full max-w-[1600px] space-y-9 p-4 [font-family:'DM_Sans_Variable',sans-serif] md:p-6 xl:p-8">
    <PageHeader title="Reports & Analytics" description={reportLabel} actions={<div className="flex flex-wrap items-center gap-2"><div className="flex h-9 items-center rounded-lg border border-border bg-muted/40 p-0.5" aria-label="Report period type"><Button size="sm" variant={periodMode === "month" ? "secondary" : "ghost"} className="h-7 px-2.5 text-xs" onClick={() => { setPeriodMode("month"); setMonthTo(monthFrom); }}>Month</Button><Button size="sm" variant={periodMode === "range" ? "secondary" : "ghost"} className="h-7 px-2.5 text-xs" onClick={() => setPeriodMode("range")}>Month range</Button></div><input type="month" value={monthFrom} max={currentMonth()} onChange={event => { if (!event.target.value) return; setMonthFrom(event.target.value); if (periodMode === "month" || event.target.value > monthTo) setMonthTo(event.target.value); }} aria-label={periodMode === "month" ? "Report month" : "Report start month"} className="h-9 rounded-lg border border-border bg-background px-3 text-sm text-foreground" />{periodMode === "range" && <><span className="text-sm text-muted-foreground">to</span><input type="month" value={monthTo} min={monthFrom} max={currentMonth()} onChange={event => event.target.value && setMonthTo(event.target.value)} aria-label="Report end month" className="h-9 rounded-lg border border-border bg-background px-3 text-sm text-foreground" /></>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" className="h-9"><Download className="mr-1.5 h-4 w-4" />Export</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel className="text-xs">Selected period</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onClick={() => handleExport("employees")}>Employees</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("payroll_monthly")}>Payroll monthly</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("payroll_detail")}>Payslips per employee</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("attendance")}>Availability daily</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("leaves")}>Leave requests</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>} />

    <section className="space-y-5"><SectionHeader eyebrow="Executive summary" title="Business position" className="[&_h2]:[font-family:'Space_Grotesk_Variable',sans-serif] [&_h2]:text-xl" /><div className="grid gap-4 [grid-template-columns:repeat(auto-fit,minmax(min(100%,15rem),1fr))]">
      <MetricCard label="Employer payroll cost" value={payrollMonths.length ? inr(employerCost) : "—"} helper={payrollMonths.length ? <Delta value={payrollDelta} /> : "No processed payroll in this period"} icon={CircleDollarSign} hover={hp("Employer payroll cost", [["Gross payroll", inr(payroll.gross)], ["Employer contributions", inr(payroll.er)], ["Previous period", previousEmployerCost ? inr(previousEmployerCost) : "—"], ["Joiners' cost", inr(joinerCost)], ["Leavers' cost", inr(exitCost)]])} onOpen={() => openPayrollEmployees("Employer payroll cost by employee", byEmployee)} />
      <MetricCard label="Cost per paid employee" value={paidEmployees ? inr(costPerPaidEmployee) : "—"} helper={`${paidEmployees.toLocaleString("en-IN")} paid · median gross ${inr(medianGross)}`} icon={Wallet} hover={hp("Pay spread", [["Median monthly gross", inr(medianGross)], ["Highest monthly gross", inr(monthlyGrossList[monthlyGrossList.length - 1] || 0)], ["Lowest monthly gross", inr(monthlyGrossList[0] || 0)], [`Top ${topCount} earners' share`, pct(topShare)]])} onOpen={() => openPayrollEmployees("Cost per paid employee", byEmployee)} />
      <MetricCard label="Closing headcount" value={closingHeadcount.toLocaleString("en-IN")} helper={`${joinsInRange.length} joined · ${exitsInRange.length} exited`} icon={Users} tone={closingHeadcount >= openingHeadcount ? "success" : "warning"} hover={hp("Headcount", [["Opening", openingHeadcount], ["Joined", `+${joinsInRange.length}`], ["Exited", `−${exitsInRange.length}`], ["Average tenure", `${avgTenure.toFixed(1)} months`], ["Exits within 6 months", earlyExits]])} onOpen={() => openPeople("Headcount at period end", activeAtEnd, "Tenure (months)", (e: any) => Math.round(monthsBetween(wiByEmp.get(e.id).joining_date, dateTo)))} />
      <MetricCard label="Workforce availability" value={availabilityNow.marked ? pct(availabilityNow.rate) : "—"} helper={availabilityNow.marked ? <Delta value={availabilityDelta} /> : "No attendance evidence in this period"} icon={Activity} tone={availabilityNow.rate >= 90 ? "success" : "warning"} hover={hp("Availability", [["Marked days", availabilityNow.marked], ["Equivalent days lost", availabilityNow.lost.toLocaleString("en-IN")], ["Average workday", `${availabilityNow.averageHours.toFixed(1)} h`], ["Employees below 85%", lowAvailability.length]])} onOpen={() => openAvailability()} />
    </div>
      <Card className="overflow-hidden bg-foreground text-background"><CardContent className="grid gap-x-6 gap-y-5 p-5 sm:grid-cols-2 xl:grid-cols-4 [&_.text-foreground]:text-background [&_.text-muted-foreground]:text-background/55">
        <Insight className="-m-2 p-2 hover:bg-background/10" hover={hp("Biggest movers", costMovers.slice(0, 4).map(r => [empName(r.id), `${r.change >= 0 ? "+" : ""}${inr(r.change)}`] as HoverLine))} onOpen={openMovers}><InsightItem label="PAYROLL MOVEMENT" value={payrollDelta == null ? "Comparison unavailable" : signedPct(payrollDelta)} note={`${inr(payroll.gross)} gross payroll`} tone={payrollDelta != null && payrollDelta > 5 ? "warning" : "default"} /></Insight>
        <Insight className="-m-2 p-2 hover:bg-background/10" hover={hp("Movement", [["Joined", joinsInRange.length], ["Exited", exitsInRange.length], ["Exits within 6 months", earlyExits], ["Annualised attrition", pct(attritionRate)]])} onOpen={() => openPeople("Joiners and leavers", [...joinsInRange.map((j: any) => empById.get(j.employee_id)).filter(Boolean), ...exitsInRange])}><InsightItem label="WORKFORCE MOVEMENT" value={`${joinsInRange.length - exitsInRange.length >= 0 ? "+" : ""}${joinsInRange.length - exitsInRange.length} net`} note={`${pct(attritionRate)} annualised attrition`} /></Insight>
        <Insight className="-m-2 p-2 hover:bg-background/10" hover={hp("Leave", [["Pending", pendingLeaves.length], ["Approved days", approvedLeaveDays], ["Loss of pay days", lopDays], ["Per active employee", leaveDaysPerEmployee.toFixed(1)]])} onOpen={openPending}><InsightItem label="LEAVE DECISIONS" value={`${pendingLeaves.length} pending`} note={`${approvedLeaveDays.toLocaleString("en-IN")} approved leave days`} tone={pendingLeaves.length ? "warning" : "default"} /></Insight>
        <Insight className="-m-2 p-2 hover:bg-background/10" hover={hp("Coverage", [["Payslips", filteredPayroll.length], ["With register detail", registerRows], ["Missing", filteredPayroll.length - registerRows]])} onOpen={openStatutory}><InsightItem label="SOURCE COVERAGE" value={filteredPayroll.length ? `${registerCoverage.toFixed(0)}% payroll register` : "No payroll rows"} note={registerCoverage < 100 && filteredPayroll.length ? `${filteredPayroll.length - registerRows} payslips lack register detail` : "Statutory detail fully covered"} tone={registerCoverage < 100 && filteredPayroll.length ? "danger" : "default"} /></Insight>
      </CardContent></Card>
    </section>

    <section className="space-y-5"><SectionHeader eyebrow="Payroll" title="Cost and distribution" className="[&_h2]:[font-family:'Space_Grotesk_Variable',sans-serif] [&_h2]:text-xl" />
      <div className="grid items-stretch gap-4 lg:grid-cols-[minmax(0,3fr)_minmax(17rem,1fr)]"><Card className="min-w-0"><CardHeader className="pb-2"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><CardTitle className="[font-family:'Space_Grotesk_Variable',sans-serif] text-sm">Monthly employer cost</CardTitle><p className="text-[11px] text-muted-foreground">Click a month for employees</p></div></CardHeader><CardContent className="min-w-0">{payrollChart.length ? <div className="h-[clamp(15rem,26vw,21rem)] min-h-0 w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={payrollChart} onClick={(state: any) => { const key = state?.activePayload?.[0]?.payload?.key; if (key) setDrillMonth(key); }} style={{ cursor: "pointer" }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="month" fontSize={11} /><YAxis width={44} fontSize={11} tickFormatter={value => `${Math.round(value / 1000)}K`} /><Tooltip content={({ active, payload }: any) => { if (!active || !payload?.length) return null; const d = payload[0].payload; return <div className="rounded-lg border border-border bg-popover p-3 text-xs shadow-md"><HoverPanel title={d.month} hint={false} lines={[["Paid employees", d.paidIds.size], ["Gross", inr(d.gross)], ["Employer contrib.", inr(d.er)], ["Employer cost", inr(d.employerCost)], ["Deductions", inr(d.deductions)], ["Net paid", inr(d.net)], ["Avg cost / employee", inr(d.paidIds.size ? d.employerCost / d.paidIds.size : 0)]]} /></div>; }} /><Bar dataKey="gross" name="Gross payroll" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} /><Bar dataKey="er" name="Employer contribution" fill="hsl(var(--warning))" radius={[4, 4, 0, 0]} /><Line type="monotone" dataKey="net" name="Net paid" stroke="hsl(var(--success))" strokeWidth={2} dot={{ r: 3 }} /></ComposedChart></ResponsiveContainer></div> : noData("No payslips exist for the selected period.")}</CardContent></Card>
        <Card className="min-w-0"><CardHeader className="pb-2"><CardTitle className="[font-family:'Space_Grotesk_Variable',sans-serif] text-sm">Payroll bridge</CardTitle></CardHeader><CardContent className="flex h-[calc(100%-3.5rem)] flex-col gap-4">{payrollMonths.length ? <>{[{ label: "Gross payroll", value: payroll.gross, tone: "bg-primary", go: () => openComposition() }, { label: "Employee deductions", value: payroll.deductions, tone: "bg-destructive", go: openStatutory }, { label: "Net paid", value: payroll.net, tone: "bg-success", go: () => openPayrollEmployees("Net paid by employee", byEmployee) }, { label: "Employer contributions", value: payroll.er, tone: "bg-warning", go: openStatutory }].map(item => <Insight key={item.label} className="-mx-2 px-2 py-1 hover:bg-muted/50" hover={hp(item.label, [["Amount", inr(item.value)], ["Share of gross", pct(payroll.gross ? item.value / payroll.gross * 100 : 0)], ["Per paid employee", inr(paidEmployees ? item.value / paidEmployees : 0)]])} onOpen={item.go}><div className="mb-2 flex flex-wrap justify-between gap-x-3 gap-y-1 text-xs"><span className="text-muted-foreground">{item.label}</span><span className="font-semibold tabular-nums text-foreground">{inr(item.value)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${item.tone}`} style={{ width: `${payroll.gross ? Math.max(2, Math.min(100, item.value / payroll.gross * 100)) : 0}%` }} /></div></Insight>)}<div className="mt-auto border-t border-dashed border-border pt-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><span className="text-[11px] font-semibold uppercase text-muted-foreground">Employer payroll cost</span><span className="font-bold tabular-nums text-foreground [font-family:'Space_Grotesk_Variable',sans-serif] text-lg">{inr(employerCost)}</span></div></div></> : noData("No payroll bridge is available.")}</CardContent></Card></div>

      <div className="grid gap-4 [grid-template-columns:repeat(auto-fit,minmax(min(100%,13rem),1fr))]">
        <MetricCard label="Variable pay share" value={payrollMonths.length ? pct(variableShare) : "—"} helper={`${inr(variablePay)} overtime, incentives, one-time`} icon={ArrowUpRight} tone={variableShare > 15 ? "warning" : "primary"} hover={hp("Variable pay", [["Variable", inr(variablePay)], ["Fixed", inr(payroll.gross - variablePay)], ["Employees with variable", byEmployee.filter(r => r.variable > 0).length]])} onOpen={openComposition} />
        <MetricCard label={`Top ${topCount} earners' share`} value={payrollMonths.length ? pct(topShare) : "—"} helper="Share of gross payroll" icon={Landmark} tone={topShare > 30 ? "warning" : "primary"} hover={hp("Concentration", byEmployee.slice().sort((a, b) => b.gross - a.gross).slice(0, Math.min(5, topCount)).map(r => [empName(r.id), inr(r.gross)] as HoverLine))} onOpen={() => openPayrollEmployees(`Top ${topCount} earners`, byEmployee.slice().sort((a, b) => b.gross - a.gross).slice(0, topCount))} />
        <MetricCard label="Recoveries" value={inr(recoveries)} helper={`${byEmployee.filter(r => r.recovery > 0).length} employees · loans and one-time`} icon={Wallet} hover={hp("Recoveries", byEmployee.filter(r => r.recovery > 0).sort((a, b) => b.recovery - a.recovery).slice(0, 4).map(r => [empName(r.id), inr(r.recovery)] as HoverLine))} onOpen={openRecoveries} />
        <MetricCard label="Joiner vs leaver cost" value={`${inr(joinerCost)} / ${inr(exitCost)}`} helper="Employer cost in this period" icon={Users} hover={hp("Turnover cost", [["Joiners paid", byEmployee.filter(r => joinsInRange.some((j: any) => j.employee_id === r.id)).length], ["Leavers paid", byEmployee.filter(r => exitsInRange.some((e: any) => e.id === r.id)).length]])} onOpen={() => openPayrollEmployees("Joiners and leavers on payroll", byEmployee.filter(r => joinsInRange.some((j: any) => j.employee_id === r.id) || exitsInRange.some((e: any) => e.id === r.id)))} />
      </div>

      <div className="grid gap-4 xl:grid-cols-[1.35fr_0.85fr]"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Department payroll mix</CardTitle></CardHeader><CardContent>{departmentInsights.some(row => row.gross > 0) ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead><tr className="border-b border-border text-left text-muted-foreground"><th className="pb-2 font-medium">Department</th><th className="pb-2 text-right font-medium">Paid</th><th className="pb-2 text-right font-medium">Gross</th><th className="pb-2 text-right font-medium">Cost / paid employee</th><th className="pb-2 text-right font-medium">Headcount share</th><th className="pb-2 text-right font-medium">Payroll share</th></tr></thead><tbody>{departmentInsights.filter(row => row.gross > 0).map(row => <tr key={row.name} onClick={() => openDepartment(row.name)} className="cursor-pointer border-b border-border/60 last:border-0 hover:bg-muted/40"><td className="py-2.5 font-medium text-foreground">{row.name}</td><td className="py-2.5 text-right tabular-nums">{row.paid}</td><td className="py-2.5 text-right font-medium tabular-nums">{inr(row.gross)}</td><td className="py-2.5 text-right tabular-nums text-muted-foreground">{inr(row.costPerPaid)}</td><td className="py-2.5 text-right tabular-nums text-muted-foreground">{pct(row.headcountShare)}</td><td className={`py-2.5 text-right tabular-nums ${row.payrollShare - row.headcountShare > 10 ? "text-warning" : ""}`}>{pct(row.payrollShare)}</td></tr>)}</tbody></table></div> : noData("No departmental payroll is available.")}</CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Monthly gross bands</CardTitle></CardHeader><CardContent className="space-y-3">{monthlyGrossList.length ? salaryBands.map(band => <Insight key={band.name} className="-mx-2 px-2 py-1 hover:bg-muted/50" hover={hp(band.name, [["Payslips", band.count], ["Gross", inr(band.gross)], ["Share of gross", pct(payroll.gross ? band.gross / payroll.gross * 100 : 0)]])} onOpen={() => openBand(band)}><RankedBar label={band.name} value={band.count} max={Math.max(...salaryBands.map(b => b.count))} suffix=" payslips" detail={`${inr(band.gross)} gross`} /></Insight>) : noData("No payslips in this period.")}<button onClick={openStatutory} className="w-full border-t border-border pt-3 text-left text-xs text-muted-foreground hover:text-foreground">Statutory: PF {inr(payroll.pf)} · ESI {inr(payroll.esi)} · PT {inr(payroll.pt)} · TDS {inr(payroll.tds)} →</button>{registerCoverage < 100 && filteredPayroll.length > 0 && <div className="flex gap-2 rounded-lg border border-warning/30 bg-warning/5 p-3 text-[11px] leading-relaxed text-muted-foreground"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-warning" /><span>Only {registerRows} of {filteredPayroll.length} payslips have register detail. Statutory totals may be understated.</span></div>}</CardContent></Card></div>
    </section>

    <section className="space-y-3"><SectionHeader eyebrow="Workforce" title="Movement and structure" />
      <div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Headcount movement</CardTitle></CardHeader><CardContent><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] items-center gap-2 text-center"><div><p className="text-2xl font-semibold tabular-nums">{openingHeadcount}</p><p className="text-[10px] text-muted-foreground">Opening</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /><Insight className="hover:bg-muted/50" onOpen={() => openPeople("Joined", joinsInRange.map((j: any) => empById.get(j.employee_id)).filter(Boolean))}><p className="text-2xl font-semibold tabular-nums text-success">+{joinsInRange.length}</p><p className="text-[10px] text-muted-foreground">Joined</p></Insight><ArrowRight className="h-4 w-4 text-muted-foreground" /><Insight className="hover:bg-muted/50" onOpen={() => openPeople("Exited", exitsInRange, "Tenure (months)", (e: any) => { const j = wiByEmp.get(e.id)?.joining_date; return j ? Math.round(monthsBetween(j, exitDateOf(e))) : "—"; })}><p className="text-2xl font-semibold tabular-nums text-destructive">−{exitsInRange.length}</p><p className="text-[10px] text-muted-foreground">Exited</p></Insight><ArrowRight className="h-4 w-4 text-muted-foreground" /><div><p className="text-2xl font-semibold tabular-nums">{closingHeadcount}</p><p className="text-[10px] text-muted-foreground">Closing</p></div></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-border pt-4"><InsightItem label="ACTIVE TODAY" value={activeCount} /><InsightItem label="ATTRITION" value={pct(attritionRate)} tone={attritionRate > 20 ? "warning" : "default"} /><InsightItem label="EARLY EXITS" value={earlyExits} note="< 6 months" tone={earlyExits ? "warning" : "default"} /></div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Department concentration</CardTitle></CardHeader><CardContent className="space-y-2">{departmentInsights.length ? departmentInsights.map(row => <Insight key={row.name} className="-mx-2 px-2 py-1 hover:bg-muted/50" hover={hp(row.name, [["Active", row.active], ["Paid", row.paid], ["Gross", inr(row.gross)], ["Cost / paid", inr(row.costPerPaid)], ["Leave days", leaveByDepartment.find(l => l.name === row.name)?.days || 0]])} onOpen={() => openDepartment(row.name)}><RankedBar label={row.name} value={row.gross} max={maxDepartmentGross} detail={`${row.active} active · ${pct(row.payrollShare)} of payroll`} /></Insight>) : noData("No department mapping is available.")}</CardContent></Card></div>
      <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Tenure profile</CardTitle></CardHeader><CardContent className="space-y-2">{tenureBands.map(band => <Insight key={band.name} className="-mx-2 px-2 py-1 hover:bg-muted/50" onOpen={() => openPeople(`Tenure ${band.name}`, band.people)}><RankedBar label={band.name} value={band.count} max={Math.max(...tenureBands.map(b => b.count))} suffix=" people" /></Insight>)}<p className="border-t border-border pt-2 text-xs text-muted-foreground">Average {avgTenure.toFixed(1)} months</p></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Employment mix</CardTitle></CardHeader><CardContent className="space-y-1">{employeeTypes.map((row, index) => <Insight key={row.name} className="-mx-2 flex items-center gap-3 px-2 py-1.5 hover:bg-muted/50" onOpen={() => openPeople(`${row.name} employees`, employees.filter((e: any) => e.is_active && (wiByEmp.get(e.id)?.employee_type || "Unspecified") === row.name))}><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} /><span className="min-w-0 flex-1 truncate text-xs font-medium capitalize text-foreground">{row.name}</span><span className="text-xs tabular-nums text-muted-foreground">{row.count} · {pct(row.share)}</span></Insight>)}</CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Data readiness</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Insight className="hover:bg-muted/50" onOpen={() => openPeople("Missing joining date", employees.filter((e: any) => !wiByEmp.get(e.id)?.joining_date))}><InsightItem label="MISSING JOINING DATE" value={missingJoiningDates} tone={missingJoiningDates ? "warning" : "default"} /></Insight><Insight className="hover:bg-muted/50" onOpen={() => openPeople("Unmapped department", employees.filter((e: any) => e.is_active && !wiByEmp.get(e.id)?.department_id))}><InsightItem label="UNMAPPED DEPARTMENT" value={unmappedDepartments} tone={unmappedDepartments ? "warning" : "default"} /></Insight></CardContent></Card></div>
    </section>

    <section className="space-y-3"><SectionHeader eyebrow="Leave & availability" title="Capacity impact" />
      <div className="grid gap-4 xl:grid-cols-3"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Leave position</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><Insight className="hover:bg-muted/50" onOpen={() => openLeave()}><InsightItem label="APPROVED DAYS" value={approvedLeaveDays.toLocaleString("en-IN")} note={`${leaveDaysPerEmployee.toFixed(1)} per active employee`} /></Insight><Insight className="hover:bg-muted/50" onOpen={openPending}><InsightItem label="PENDING DECISIONS" value={pendingLeaves.length} tone={pendingLeaves.length ? "warning" : "default"} /></Insight><div className="col-span-2 border-t border-border pt-3"><p className="mb-2 text-[11px] font-semibold text-muted-foreground">APPROVED DAYS BY TYPE</p>{leaveByType.length ? <div className="space-y-1">{leaveByType.map(row => <Insight key={row.name} className="-mx-2 flex justify-between gap-3 px-2 py-1 text-xs hover:bg-muted/50" onOpen={() => openLeave(leaveByEmp.filter(r => r.types[row.name]), `${row.name} by employee`)}><span className="text-foreground">{row.name}</span><span className="font-semibold tabular-nums">{row.days.toLocaleString("en-IN")} · {pct(approvedLeaveDays ? row.days / approvedLeaveDays * 100 : 0)}</span></Insight>)}</div> : <p className="text-xs text-muted-foreground">No approved leave in this period.</p>}</div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Top leave takers</CardTitle></CardHeader><CardContent className="space-y-2">{leaveByEmp.length ? leaveByEmp.slice(0, 6).map(r => <Insight key={r.id} className="-mx-2 px-2 py-1 hover:bg-muted/50" hover={hp(empName(r.id), Object.entries(r.types).map(([t, d]) => [t, `${d} days`] as HoverLine))} onOpen={() => openLeave([r], empName(r.id))}><RankedBar label={empName(r.id)} value={r.days} max={leaveByEmp[0].days} suffix=" days" detail={deptOf(r.id)} /></Insight>) : noData("No approved leave days in this period.")}{leaveByEmp.length > 6 && <button onClick={() => openLeave()} className="text-xs text-primary hover:underline">View all {leaveByEmp.length} →</button>}</CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Workforce availability</CardTitle></CardHeader><CardContent className="space-y-4"><Insight className="hover:bg-muted/50" onOpen={() => openAvailability()}><p className="text-3xl font-semibold tabular-nums text-foreground">{availabilityNow.marked ? pct(availabilityNow.rate) : "—"}</p><div className="mt-1 text-xs text-muted-foreground"><Delta value={availabilityDelta} /></div></Insight><div className="grid grid-cols-2 gap-3 border-t border-border pt-4"><InsightItem label="EQUIVALENT DAYS LOST" value={availabilityNow.lost.toLocaleString("en-IN")} /><InsightItem label="AVERAGE WORKDAY" value={`${availabilityNow.averageHours.toFixed(1)} h`} /></div>{lowAvailability.length > 0 && <button onClick={() => openAvailability(lowAvailability, "Employees below 85% availability")} className="w-full rounded-lg border border-warning/30 bg-warning/5 p-2.5 text-left text-xs text-foreground hover:bg-warning/10">{lowAvailability.length} employees below 85% →</button>}</CardContent></Card></div>
    </section>

    <Card className="border-dashed"><CardContent className="flex items-start gap-3 p-4"><Landmark className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" /><div><p className="text-xs font-semibold text-foreground">Methodology</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Payroll uses the RazorpayX payslip mirror. Employer payroll cost = gross payroll + employer contributions. Headcount uses actual joining and exit dates. Leave counts approved days only. Availability uses evidence-backed attendance days. Owners/directors are excluded from every figure, drill-down and export.</p></div></CardContent></Card>

    <MonthlyPayrollBreakdownDialog monthKey={drillMonth} monthLabel={drillMonth ? monthLabel(drillMonth) : ""} onClose={() => setDrillMonth(null)} empName={empName} deptOf={deptOf} excludeEmployeeIds={excludedEmployeeIds} empBadge={id => (empById.get(id) as any)?.badge_id || "—"} />
    <DetailDialog spec={detail} onClose={() => setDetail(null)} />
  </div></TooltipProvider>;
}
