import { useEffect, useMemo, useState, type ReactNode } from "react";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { fetchAllPaginated } from "@/lib/fetchAllRows";
import { fetchAttendanceDayRange } from "@/hooks/hrms/useAttendanceDay";
import { splitOwnerStats } from "@/lib/ownerStatsExclusion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Tooltip as UiTooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, AlertCircle, ArrowDownRight, ArrowRight, ArrowUpRight, CircleDollarSign, Download, Info, Landmark, Minus, Users, Wallet } from "lucide-react";
import * as XLSX from "xlsx";
import { PageHeader } from "@/components/shared/PageHeader";
import { SectionHeader } from "@/components/hrms/primitives/SectionHeader";
import { MonthlyPayrollBreakdownDialog } from "@/components/hrms/MonthlyPayrollBreakdownDialog";

const COLORS = ["hsl(var(--primary))", "hsl(var(--success))", "hsl(var(--warning))", "hsl(var(--destructive))", "hsl(var(--info))", "hsl(var(--muted-foreground))"];
const PAID_LEAVE_STATUSES = new Set(["approved", "manager_approved"]);
const PENDING_LEAVE_STATUSES = new Set(["requested", "pending"]);
const inr = (n: number) => `₹${Math.round(n || 0).toLocaleString("en-IN")}`;
const pct = (n: number) => `${Number.isFinite(n) ? n.toFixed(1) : "0.0"}%`;
const monthLabel = (iso: string) => new Date(`${iso.slice(0, 7)}-01T00:00:00`).toLocaleDateString("en-IN", { month: "short", year: "2-digit" });
const currentMonth = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`; };
const lastDayOfMonth = (month: string) => { const [year, number] = month.split("-").map(Number); return `${month}-${String(new Date(year, number, 0).getDate()).padStart(2, "0")}`; };
const shiftMonth = (month: string, offset: number) => { const [year, number] = month.split("-").map(Number); const date = new Date(year, number - 1 + offset, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; };
const signedPct = (value: number | null) => value == null ? "No comparison" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}% vs previous`;

type PayrollMonth = { key: string; month: string; gross: number; net: number; deductions: number; tds: number; pf: number; esi: number; pt: number; er: number; count: number; paidIds: Set<string>; withRegister: number; esiCovered: number };

function MetricCard({ label, value, helper, icon: Icon, tone = "primary" }: { label: string; value: ReactNode; helper: ReactNode; icon: typeof Users; tone?: "primary" | "success" | "warning" | "destructive" }) {
  const tones = { primary: "bg-primary/10 text-primary", success: "bg-success/10 text-success", warning: "bg-warning/10 text-warning", destructive: "bg-destructive/10 text-destructive" };
  return <Card className="min-w-0 overflow-hidden"><CardContent className="flex h-full min-h-[9rem] flex-col p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><p className="max-w-[75%] text-[11px] font-semibold uppercase leading-snug text-muted-foreground">{label}</p><span className={`inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${tones[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-4 font-semibold tabular-nums text-foreground [font-family:'Space_Grotesk_Variable',sans-serif] text-[clamp(1.5rem,2.2vw,2rem)] leading-none">{value}</p><div className="mt-auto border-t border-border/60 pt-3 text-[11px] leading-snug text-muted-foreground">{helper}</div></CardContent></Card>;
}

function Delta({ value, invert = false }: { value: number | null; invert?: boolean }) {
  if (value == null || Math.abs(value) < 0.05) return <span className="inline-flex items-center gap-1"><Minus className="h-3 w-3" />{value == null ? "No comparison" : "No change"}</span>;
  const good = invert ? value < 0 : value > 0;
  const Icon = value > 0 ? ArrowUpRight : ArrowDownRight;
  return <span className={`inline-flex items-center gap-1 font-medium ${good ? "text-success" : "text-destructive"}`}><Icon className="h-3 w-3" />{signedPct(value)}</span>;
}

function InsightItem({ label, value, note, tone = "default" }: { label: string; value: ReactNode; note?: string; tone?: "default" | "warning" | "danger" }) {
  return <div className="min-w-0"><p className="text-[10px] font-semibold uppercase text-muted-foreground">{label}</p><p className={`mt-1 text-sm font-semibold tabular-nums ${tone === "danger" ? "text-destructive" : tone === "warning" ? "text-warning" : "text-foreground"}`}>{value}</p>{note && <p className="mt-0.5 text-[11px] leading-snug text-muted-foreground">{note}</p>}</div>;
}

function RankedBar({ label, value, max, suffix, detail }: { label: string; value: number; max: number; suffix?: string; detail?: string }) {
  return <div className="space-y-1.5"><div className="flex items-center justify-between gap-3 text-xs"><span className="min-w-0 truncate font-medium text-foreground">{label}</span><span className="shrink-0 tabular-nums text-muted-foreground">{value.toLocaleString("en-IN")}{suffix}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${max ? Math.max(2, value / max * 100) : 0}%` }} /></div>{detail && <p className="text-[10px] text-muted-foreground">{detail}</p>}</div>;
}

export default function ReportsPage() {
  const [periodMode, setPeriodMode] = useState<"month" | "range">("month");
  const [monthFrom, setMonthFrom] = useState(currentMonth);
  const [monthTo, setMonthTo] = useState(currentMonth);
  const [defaultsApplied, setDefaultsApplied] = useState(false);
  const [drillMonth, setDrillMonth] = useState<string | null>(null);
  const dateFrom = `${monthFrom}-01`;
  const dateTo = lastDayOfMonth(periodMode === "month" ? monthFrom : monthTo);

  const prevWindow = useMemo(() => {
    const [fy, fm] = monthFrom.split("-").map(Number);
    const [ty, tm] = (periodMode === "month" ? monthFrom : monthTo).split("-").map(Number);
    const count = Math.max(1, (ty - fy) * 12 + tm - fm + 1);
    const toMonth = shiftMonth(monthFrom, -1);
    const fromMonth = shiftMonth(monthFrom, -count);
    return { from: `${fromMonth}-01`, to: lastDayOfMonth(toMonth) };
  }, [monthFrom, monthTo, periodMode]);

  const { data: latestProcessedMonth } = useQuery({ queryKey: ["rpt_latest_processed_month"], queryFn: async () => { const { data } = await supabase.from("hr_payslips_v").select("period_month").order("period_month", { ascending: false }).limit(1); return (data?.[0]?.period_month as string | undefined)?.slice(0, 7) ?? null; }, staleTime: 60_000 });
  useEffect(() => { if (defaultsApplied || !latestProcessedMonth) return; setDefaultsApplied(true); setPeriodMode("month"); setMonthFrom(latestProcessedMonth); setMonthTo(latestProcessedMonth); }, [defaultsApplied, latestProcessedMonth]);

  const { data: allEmployees = [] } = useQuery({ queryKey: ["rpt_employees"], queryFn: () => fetchAllPaginated<any>(() => supabase.from("hr_employees").select("id, badge_id, first_name, last_name, is_active, total_salary, resignation_date, last_working_day")) });
  const { kept: employees, excludedIds: excludedEmployeeIds } = useMemo(() => splitOwnerStats(allEmployees), [allEmployees]);
  const employeeIds = useMemo(() => employees.map((employee: any) => employee.id), [employees]);
  const employeeKey = employeeIds.join(",");
  const { data: workInfos = [] } = useQuery({ queryKey: ["rpt_work_infos"], queryFn: () => fetchAllPaginated<any>(() => supabase.from("hr_employee_work_info").select("employee_id, employee_type, department_id, joining_date, job_position_id")) });
  const { data: departments = [] } = useQuery({ queryKey: ["rpt_departments"], queryFn: async () => { const { data } = await supabase.from("departments").select("id, name"); return data || []; } });
  const { data: leaveRequests = [] } = useQuery({ queryKey: ["rpt_leaves"], queryFn: () => fetchAllPaginated<any>(() => supabase.from("hr_leave_requests").select("id, employee_id, status, total_days, leave_type_id, start_date, end_date, created_at")) });
  const { data: leaveTypes = [] } = useQuery({ queryKey: ["rpt_leave_types"], queryFn: async () => { const { data } = await supabase.from("hr_leave_types").select("id, name"); return data || []; } });

  const payrollSelect = "employee_id, period_month, gross, regular_gross, net, total_deductions, tds_amount, pf_amount, esi_amount, professional_tax, employer_contrib, register_source";
  const { data: payslips = [] } = useQuery({ queryKey: ["rpt_payslips", dateFrom, dateTo], placeholderData: keepPreviousData, queryFn: () => fetchAllPaginated<any>(() => (supabase as any).from("hr_payslips_v").select(payrollSelect).gte("period_month", dateFrom).lte("period_month", dateTo)) });
  const { data: previousPayslips = [] } = useQuery({ queryKey: ["rpt_payslips_previous", prevWindow.from, prevWindow.to], placeholderData: keepPreviousData, queryFn: () => fetchAllPaginated<any>(() => (supabase as any).from("hr_payslips_v").select(payrollSelect).gte("period_month", prevWindow.from).lte("period_month", prevWindow.to)) });
  const { data: attendance = [] } = useQuery({ queryKey: ["rpt_availability", dateFrom, dateTo, employeeKey], enabled: employeeIds.length > 0, placeholderData: keepPreviousData, queryFn: async () => (await fetchAttendanceDayRange(employeeIds, dateFrom, dateTo)).filter(day => day.evidence_backed) });
  const { data: prevAttendance = [] } = useQuery({ queryKey: ["rpt_availability_previous", prevWindow.from, prevWindow.to, employeeKey], enabled: employeeIds.length > 0, placeholderData: keepPreviousData, queryFn: async () => (await fetchAttendanceDayRange(employeeIds, prevWindow.from, prevWindow.to)).filter(day => day.evidence_backed) });

  const empById = useMemo(() => new Map(employees.map((e: any) => [e.id, e])), [employees]);
  const wiByEmp = useMemo(() => new Map(workInfos.map((w: any) => [w.employee_id, w])), [workInfos]);
  const deptById = useMemo(() => new Map(departments.map((d: any) => [d.id, d.name])), [departments]);
  const empName = (id: string) => { const employee: any = empById.get(id); return employee ? `${employee.first_name || ""} ${employee.last_name || ""}`.trim() || employee.badge_id || id : id; };
  const deptOf = (id: string) => deptById.get(wiByEmp.get(id)?.department_id) || "Unassigned";
  const exitDateOf = (employee: any) => employee.last_working_day || employee.resignation_date || null;
  const inRange = (date?: string | null) => !!date && date.slice(0, 10) >= dateFrom && date.slice(0, 10) <= dateTo;

  const filteredPayroll = useMemo(() => payslips.filter((p: any) => !excludedEmployeeIds.has(p.employee_id)), [payslips, excludedEmployeeIds]);
  const filteredPreviousPayroll = useMemo(() => previousPayslips.filter((p: any) => !excludedEmployeeIds.has(p.employee_id)), [previousPayslips, excludedEmployeeIds]);
  const aggregatePayroll = (rows: any[]): PayrollMonth[] => {
    const months: Record<string, PayrollMonth> = {};
    rows.forEach((p: any) => { const key = String(p.period_month).slice(0, 7); const row = months[key] || (months[key] = { key, month: monthLabel(key), gross: 0, net: 0, deductions: 0, tds: 0, pf: 0, esi: 0, pt: 0, er: 0, count: 0, paidIds: new Set(), withRegister: 0, esiCovered: 0 }); row.gross += Number(p.gross || 0); row.net += Number(p.net || 0); row.deductions += Math.abs(Number(p.total_deductions || 0)); row.tds += Math.abs(Number(p.tds_amount || 0)); row.pf += Math.abs(Number(p.pf_amount || 0)); row.esi += Math.abs(Number(p.esi_amount || 0)); row.pt += Math.abs(Number(p.professional_tax || 0)); row.er += Number(p.employer_contrib || 0); row.count++; row.paidIds.add(p.employee_id); if (p.register_source) row.withRegister++; if (Math.abs(Number(p.esi_amount || 0)) > 0) row.esiCovered++; });
    return Object.values(months).sort((a, b) => a.key.localeCompare(b.key));
  };
  const payrollMonths = useMemo(() => aggregatePayroll(filteredPayroll), [filteredPayroll]);
  const previousPayrollMonths = useMemo(() => aggregatePayroll(filteredPreviousPayroll), [filteredPreviousPayroll]);
  const sumPayroll = (rows: PayrollMonth[]) => rows.reduce((sum, row) => ({ gross: sum.gross + row.gross, net: sum.net + row.net, deductions: sum.deductions + row.deductions, er: sum.er + row.er, pf: sum.pf + row.pf, esi: sum.esi + row.esi, pt: sum.pt + row.pt, tds: sum.tds + row.tds }), { gross: 0, net: 0, deductions: 0, er: 0, pf: 0, esi: 0, pt: 0, tds: 0 });
  const payroll = useMemo(() => sumPayroll(payrollMonths), [payrollMonths]);
  const previousPayroll = useMemo(() => sumPayroll(previousPayrollMonths), [previousPayrollMonths]);
  const employerCost = payroll.gross + payroll.er;
  const previousEmployerCost = previousPayroll.gross + previousPayroll.er;
  const payrollDelta = previousEmployerCost ? (employerCost - previousEmployerCost) / previousEmployerCost * 100 : null;
  const paidEmployees = useMemo(() => new Set(filteredPayroll.map((row: any) => row.employee_id)).size, [filteredPayroll]);
  const costPerPaidEmployee = paidEmployees ? employerCost / paidEmployees : 0;
  const registerRows = payrollMonths.reduce((sum, row) => sum + row.withRegister, 0);
  const registerCoverage = filteredPayroll.length ? registerRows / filteredPayroll.length * 100 : 0;

  const openingHeadcount = useMemo(() => employees.filter((e: any) => { const joined = wiByEmp.get(e.id)?.joining_date; const exit = exitDateOf(e); return joined && joined < dateFrom && (!exit || exit >= dateFrom); }).length, [employees, wiByEmp, dateFrom]);
  const joinsInRange = useMemo(() => workInfos.filter((w: any) => empById.has(w.employee_id) && inRange(w.joining_date)), [workInfos, empById, dateFrom, dateTo]);
  const exitsInRange = useMemo(() => employees.filter((e: any) => inRange(exitDateOf(e))), [employees, dateFrom, dateTo]);
  const closingHeadcount = openingHeadcount + joinsInRange.length - exitsInRange.length;
  const activeCount = employees.filter((employee: any) => employee.is_active).length;
  const averageHeadcount = Math.max(0, (openingHeadcount + closingHeadcount) / 2);
  const monthSpan = Math.max(1, ((Number((periodMode === "month" ? monthFrom : monthTo).slice(0, 4)) - Number(monthFrom.slice(0, 4))) * 12) + Number((periodMode === "month" ? monthFrom : monthTo).slice(5, 7)) - Number(monthFrom.slice(5, 7)) + 1);
  const attritionRate = averageHeadcount ? exitsInRange.length / averageHeadcount * (12 / monthSpan) * 100 : 0;

  const availability = (rows: any[]) => { let present = 0, half = 0, absent = 0, incomplete = 0, minutes = 0, worked = 0; rows.forEach((row: any) => { if (row.status === "present") present++; else if (row.status === "half_day") half++; else if (row.status === "absent") absent++; else if (row.status === "incomplete") incomplete++; const value = Number(row.worked_minutes || 0); if (value > 0) { minutes += value; worked++; } }); const marked = present + half + absent + incomplete; const equivalentWorked = present + half * 0.5 + incomplete * 0.5; return { marked, rate: marked ? equivalentWorked / marked * 100 : 0, lost: marked - equivalentWorked, averageHours: worked ? minutes / worked / 60 : 0 }; };
  const availabilityNow = useMemo(() => availability(attendance), [attendance]);
  const availabilityPrevious = useMemo(() => availability(prevAttendance), [prevAttendance]);
  const availabilityDelta = availabilityPrevious.marked ? availabilityNow.rate - availabilityPrevious.rate : null;

  const selectedLeaves = useMemo(() => leaveRequests.filter((leave: any) => {
    if (excludedEmployeeIds.has(leave.employee_id)) return false;
    const start = String(leave.start_date || leave.created_at || "").slice(0, 10);
    const end = String(leave.end_date || leave.start_date || leave.created_at || "").slice(0, 10);
    return start <= dateTo && end >= dateFrom;
  }), [leaveRequests, excludedEmployeeIds, dateFrom, dateTo]);
  const approvedLeaves = useMemo(() => selectedLeaves.filter((leave: any) => PAID_LEAVE_STATUSES.has(String(leave.status || "").toLowerCase())), [selectedLeaves]);
  const pendingLeaves = useMemo(() => selectedLeaves.filter((leave: any) => PENDING_LEAVE_STATUSES.has(String(leave.status || "").toLowerCase()) && String(leave.status || "").toLowerCase() !== "approved"), [selectedLeaves]);
  const approvedLeaveDays = approvedLeaves.reduce((sum: number, leave: any) => sum + Number(leave.total_days || 0), 0);
  const leaveDaysPerEmployee = activeCount ? approvedLeaveDays / activeCount : 0;
  const leaveTypeName = (id: string) => leaveTypes.find((type: any) => type.id === id)?.name || "Unassigned";
  const leaveByType = useMemo(() => { const map: Record<string, number> = {}; approvedLeaves.forEach((leave: any) => { const label = leaveTypeName(leave.leave_type_id); map[label] = (map[label] || 0) + Number(leave.total_days || 0); }); return Object.entries(map).map(([name, days]) => ({ name, days })).sort((a, b) => b.days - a.days); }, [approvedLeaves, leaveTypes]);
  const leaveByDepartment = useMemo(() => { const map: Record<string, number> = {}; approvedLeaves.forEach((leave: any) => { const name = deptOf(leave.employee_id); map[name] = (map[name] || 0) + Number(leave.total_days || 0); }); return Object.entries(map).map(([name, days]) => ({ name, days })).sort((a, b) => b.days - a.days); }, [approvedLeaves, wiByEmp, deptById]);

  const departmentInsights = useMemo(() => { const map: Record<string, { name: string; active: number; gross: number; paidIds: Set<string> }> = {}; employees.filter((e: any) => e.is_active).forEach((e: any) => { const name = deptOf(e.id); const row = map[name] || (map[name] = { name, active: 0, gross: 0, paidIds: new Set() }); row.active++; }); filteredPayroll.forEach((p: any) => { const name = deptOf(p.employee_id); const row = map[name] || (map[name] = { name, active: 0, gross: 0, paidIds: new Set() }); row.gross += Number(p.gross || 0); row.paidIds.add(p.employee_id); }); return Object.values(map).map(row => ({ ...row, paid: row.paidIds.size, costPerPaid: row.paidIds.size ? row.gross / row.paidIds.size : 0, headcountShare: activeCount ? row.active / activeCount * 100 : 0, payrollShare: payroll.gross ? row.gross / payroll.gross * 100 : 0 })).sort((a, b) => b.gross - a.gross); }, [employees, filteredPayroll, activeCount, payroll.gross, wiByEmp, deptById]);
  const employeeTypes = useMemo(() => { const map: Record<string, number> = {}; workInfos.forEach((info: any) => { if (!empById.get(info.employee_id)?.is_active) return; const name = info.employee_type || "Unspecified"; map[name] = (map[name] || 0) + 1; }); return Object.entries(map).map(([name, count]) => ({ name, count, share: activeCount ? count / activeCount * 100 : 0 })).sort((a, b) => b.count - a.count); }, [workInfos, empById, activeCount]);
  const missingJoiningDates = employees.filter((employee: any) => !wiByEmp.get(employee.id)?.joining_date).length;
  const unmappedDepartments = employees.filter((employee: any) => employee.is_active && !wiByEmp.get(employee.id)?.department_id).length;
  const maxDepartmentGross = Math.max(0, ...departmentInsights.map(row => row.gross));
  const maxLeaveDays = Math.max(0, ...leaveByDepartment.map(row => row.days));

  const reportLabel = periodMode === "month" ? new Date(`${monthFrom}-01T00:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" }) : `${monthLabel(monthFrom)} – ${monthLabel(monthTo)}`;
  const payrollChart = payrollMonths.map(row => ({ ...row, employerCost: row.gross + row.er }));

  const handleExport = (type: string) => {
    let rows: any[] = []; let name = "Report";
    if (type === "employees") { name = "Employees"; rows = employees.map((e: any) => ({ "Badge ID": e.badge_id, Name: empName(e.id), Department: deptOf(e.id), "Employee Type": wiByEmp.get(e.id)?.employee_type || "", "Joining Date": wiByEmp.get(e.id)?.joining_date || "", Active: e.is_active ? "Yes" : "No", "Exit Date": exitDateOf(e) || "", CTC: Number(e.total_salary || 0) })); }
    if (type === "leaves") { name = "Leaves"; rows = selectedLeaves.map((l: any) => ({ Employee: empName(l.employee_id), Department: deptOf(l.employee_id), Type: leaveTypeName(l.leave_type_id), Status: l.status, Days: Number(l.total_days || 0), "Start Date": l.start_date, "End Date": l.end_date })); }
    if (type === "payroll_monthly") { name = "Payroll Monthly"; rows = payrollMonths.map(row => ({ Month: row.month, "Paid Employees": row.paidIds.size, "Gross Payroll": row.gross, "Employer Contribution": row.er, "Employer Payroll Cost": row.gross + row.er, Deductions: row.deductions, "Net Paid": row.net, TDS: row.tds, PF: row.pf, ESI: row.esi, PT: row.pt })); }
    if (type === "payroll_detail") { name = "Payslips"; rows = filteredPayroll.map((p: any) => ({ Month: String(p.period_month).slice(0, 7), "Badge ID": empById.get(p.employee_id)?.badge_id || "", Employee: empName(p.employee_id), Department: deptOf(p.employee_id), "Gross Payroll": Number(p.gross || 0), "Employer Contribution": Number(p.employer_contrib || 0), "Employer Payroll Cost": Number(p.gross || 0) + Number(p.employer_contrib || 0), Deductions: Math.abs(Number(p.total_deductions || 0)), "Net Paid": Number(p.net || 0), TDS: Math.abs(Number(p.tds_amount || 0)), PF: Math.abs(Number(p.pf_amount || 0)), ESI: Math.abs(Number(p.esi_amount || 0)), PT: Math.abs(Number(p.professional_tax || 0)) })); }
    if (type === "attendance") { name = "Availability"; rows = attendance.map((a: any) => ({ Date: a.date, "Badge ID": empById.get(a.employee_id)?.badge_id || "", Employee: empName(a.employee_id), Department: deptOf(a.employee_id), Status: a.status, "Worked Minutes": Number(a.worked_minutes || 0) })); }
    if (!rows.length) rows = [{ Note: "No data in the selected period" }];
    const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), name); XLSX.writeFile(book, `${name.toLowerCase().replace(/\s+/g, "_")}_${periodMode === "month" ? monthFrom : `${monthFrom}_to_${monthTo}`}.xlsx`);
  };

  const noData = (reason: string) => <div className="py-10 text-center"><p className="text-sm font-medium text-foreground">No data available</p><p className="mt-1 text-xs text-muted-foreground">{reason}</p></div>;

  return <TooltipProvider><div className="page-mount mx-auto w-full max-w-[1600px] space-y-9 p-4 [font-family:'DM_Sans_Variable',sans-serif] md:p-6 xl:p-8">
    <PageHeader title="Reports & Analytics" description={reportLabel} actions={<div className="flex flex-wrap items-center gap-2"><div className="flex h-9 items-center rounded-lg border border-border bg-muted/40 p-0.5" aria-label="Report period type"><Button size="sm" variant={periodMode === "month" ? "secondary" : "ghost"} className="h-7 px-2.5 text-xs" onClick={() => { setPeriodMode("month"); setMonthTo(monthFrom); }}>Month</Button><Button size="sm" variant={periodMode === "range" ? "secondary" : "ghost"} className="h-7 px-2.5 text-xs" onClick={() => setPeriodMode("range")}>Month range</Button></div><input type="month" value={monthFrom} max={currentMonth()} onChange={event => { if (!event.target.value) return; setMonthFrom(event.target.value); if (periodMode === "month" || event.target.value > monthTo) setMonthTo(event.target.value); }} aria-label={periodMode === "month" ? "Report month" : "Report start month"} className="h-9 rounded-lg border border-border bg-background px-3 text-sm text-foreground" />{periodMode === "range" && <><span className="text-sm text-muted-foreground">to</span><input type="month" value={monthTo} min={monthFrom} max={currentMonth()} onChange={event => event.target.value && setMonthTo(event.target.value)} aria-label="Report end month" className="h-9 rounded-lg border border-border bg-background px-3 text-sm text-foreground" /></>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" className="h-9"><Download className="mr-1.5 h-4 w-4" />Export</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel className="text-xs">Selected period</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onClick={() => handleExport("employees")}>Employees</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("payroll_monthly")}>Payroll monthly</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("payroll_detail")}>Payslips per employee</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("attendance")}>Availability daily</DropdownMenuItem><DropdownMenuItem onClick={() => handleExport("leaves")}>Leave requests</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>} />

    <section className="space-y-5"><SectionHeader eyebrow="Executive summary" title="Business position" className="[&_h2]:[font-family:'Space_Grotesk_Variable',sans-serif] [&_h2]:text-xl" /><div className="grid gap-4 [grid-template-columns:repeat(auto-fit,minmax(min(100%,15rem),1fr))]"><MetricCard label="Employer payroll cost" value={payrollMonths.length ? inr(employerCost) : "—"} helper={payrollMonths.length ? <Delta value={payrollDelta} /> : "No processed payroll in this period"} icon={CircleDollarSign} /><MetricCard label="Cost per paid employee" value={paidEmployees ? inr(costPerPaidEmployee) : "—"} helper={`${paidEmployees.toLocaleString("en-IN")} paid employees`} icon={Wallet} /><MetricCard label="Closing headcount" value={closingHeadcount.toLocaleString("en-IN")} helper={`${joinsInRange.length} joined · ${exitsInRange.length} exited`} icon={Users} tone={closingHeadcount >= openingHeadcount ? "success" : "warning"} /><MetricCard label="Workforce availability" value={availabilityNow.marked ? pct(availabilityNow.rate) : "—"} helper={availabilityNow.marked ? <Delta value={availabilityDelta} /> : "No attendance evidence in this period"} icon={Activity} tone={availabilityNow.rate >= 90 ? "success" : "warning"} /></div>
      <Card className="overflow-hidden bg-foreground text-background"><CardContent className="grid gap-x-6 gap-y-5 p-5 sm:grid-cols-2 xl:grid-cols-4 [&_.text-foreground]:text-background [&_.text-muted-foreground]:text-background/55"><InsightItem label="PAYROLL MOVEMENT" value={payrollDelta == null ? "Comparison unavailable" : signedPct(payrollDelta)} note={`${inr(payroll.gross)} gross payroll`} tone={payrollDelta != null && payrollDelta > 5 ? "warning" : "default"} /><InsightItem label="WORKFORCE MOVEMENT" value={`${joinsInRange.length - exitsInRange.length >= 0 ? "+" : ""}${joinsInRange.length - exitsInRange.length} net`} note={`${pct(attritionRate)} annualised attrition`} /><InsightItem label="LEAVE DECISIONS" value={`${pendingLeaves.length} pending`} note={`${approvedLeaveDays.toLocaleString("en-IN")} approved leave days`} tone={pendingLeaves.length ? "warning" : "default"} /><InsightItem label="SOURCE COVERAGE" value={filteredPayroll.length ? `${registerCoverage.toFixed(0)}% payroll register` : "No payroll rows"} note={registerCoverage < 100 && filteredPayroll.length ? `${filteredPayroll.length - registerRows} payslips lack register detail` : "Statutory detail fully covered"} tone={registerCoverage < 100 && filteredPayroll.length ? "danger" : "default"} /></CardContent></Card>
    </section>

    <section className="space-y-5"><SectionHeader eyebrow="Payroll" title="Cost and distribution" className="[&_h2]:[font-family:'Space_Grotesk_Variable',sans-serif] [&_h2]:text-xl" />
      <div className="grid items-stretch gap-4 lg:grid-cols-[minmax(0,3fr)_minmax(17rem,1fr)]"><Card className="min-w-0"><CardHeader className="pb-2"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><CardTitle className="[font-family:'Space_Grotesk_Variable',sans-serif] text-sm">Monthly employer cost</CardTitle><p className="text-[11px] text-muted-foreground">Click a month for employees</p></div></CardHeader><CardContent className="min-w-0">{payrollChart.length ? <div className="h-[clamp(15rem,26vw,21rem)] min-h-0 w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={payrollChart} onClick={(state: any) => { const key = state?.activePayload?.[0]?.payload?.key; if (key) setDrillMonth(key); }} style={{ cursor: "pointer" }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="month" fontSize={11} /><YAxis width={44} fontSize={11} tickFormatter={value => `${Math.round(value / 1000)}K`} /><Tooltip formatter={(value: any) => inr(Number(value))} /><Bar dataKey="gross" name="Gross payroll" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} /><Bar dataKey="er" name="Employer contribution" fill="hsl(var(--warning))" radius={[4, 4, 0, 0]} /><Line type="monotone" dataKey="net" name="Net paid" stroke="hsl(var(--success))" strokeWidth={2} dot={{ r: 3 }} /></ComposedChart></ResponsiveContainer></div> : noData("No payslips exist for the selected period.")}</CardContent></Card>
        <Card className="min-w-0"><CardHeader className="pb-2"><CardTitle className="[font-family:'Space_Grotesk_Variable',sans-serif] text-sm">Payroll bridge</CardTitle></CardHeader><CardContent className="flex h-[calc(100%-3.5rem)] flex-col gap-5">{payrollMonths.length ? <>{[{ label: "Gross payroll", value: payroll.gross, tone: "bg-primary" }, { label: "Employee deductions", value: payroll.deductions, tone: "bg-destructive" }, { label: "Net paid", value: payroll.net, tone: "bg-success" }, { label: "Employer contributions", value: payroll.er, tone: "bg-warning" }].map(item => <div key={item.label}><div className="mb-2 flex flex-wrap justify-between gap-x-3 gap-y-1 text-xs"><span className="text-muted-foreground">{item.label}</span><span className="font-semibold tabular-nums text-foreground">{inr(item.value)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${item.tone}`} style={{ width: `${payroll.gross ? Math.max(2, Math.min(100, item.value / payroll.gross * 100)) : 0}%` }} /></div></div>)}<div className="mt-auto border-t border-dashed border-border pt-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><span className="text-[11px] font-semibold uppercase text-muted-foreground">Employer payroll cost</span><span className="font-bold tabular-nums text-foreground [font-family:'Space_Grotesk_Variable',sans-serif] text-lg">{inr(employerCost)}</span></div></div></> : noData("No payroll bridge is available.")}</CardContent></Card></div>
      <div className="grid gap-4 xl:grid-cols-[1.35fr_0.85fr]"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Department payroll mix</CardTitle></CardHeader><CardContent>{departmentInsights.some(row => row.gross > 0) ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead><tr className="border-b border-border text-left text-muted-foreground"><th className="pb-2 font-medium">Department</th><th className="pb-2 text-right font-medium">Paid</th><th className="pb-2 text-right font-medium">Gross</th><th className="pb-2 text-right font-medium">Cost / paid employee</th><th className="pb-2 text-right font-medium">Payroll share</th></tr></thead><tbody>{departmentInsights.filter(row => row.gross > 0).map(row => <tr key={row.name} className="border-b border-border/60 last:border-0"><td className="py-2.5 font-medium text-foreground">{row.name}</td><td className="py-2.5 text-right tabular-nums">{row.paid}</td><td className="py-2.5 text-right font-medium tabular-nums">{inr(row.gross)}</td><td className="py-2.5 text-right tabular-nums text-muted-foreground">{inr(row.costPerPaid)}</td><td className="py-2.5 text-right tabular-nums">{pct(row.payrollShare)}</td></tr>)}</tbody></table></div> : noData("No departmental payroll is available.")}</CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Statutory and tax detail</CardTitle></CardHeader><CardContent className="space-y-3">{payrollMonths.length ? <>{[["Provident Fund (EE)", payroll.pf], ["ESI (EE)", payroll.esi], ["Professional Tax", payroll.pt], ["TDS", payroll.tds], ["Employer contribution", payroll.er]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between gap-3 border-b border-border/60 pb-2 last:border-0"><span className="text-xs text-muted-foreground">{label}</span><span className="text-sm font-semibold tabular-nums text-foreground">{inr(Number(value))}</span></div>)}{registerCoverage < 100 && <div className="flex gap-2 rounded-lg border border-warning/30 bg-warning/5 p-3 text-[11px] leading-relaxed text-muted-foreground"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-warning" /><span>Only {registerRows} of {filteredPayroll.length} payslips have imported register detail. Statutory totals may be understated.</span></div>}</> : noData("No statutory detail is available.")}</CardContent></Card></div>
    </section>

    <section className="space-y-3"><SectionHeader eyebrow="Workforce" title="Movement and structure" />
      <div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Headcount movement</CardTitle></CardHeader><CardContent><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] items-center gap-2 text-center"><div><p className="text-2xl font-semibold tabular-nums">{openingHeadcount}</p><p className="text-[10px] text-muted-foreground">Opening</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /><div><p className="text-2xl font-semibold tabular-nums text-success">+{joinsInRange.length}</p><p className="text-[10px] text-muted-foreground">Joined</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /><div><p className="text-2xl font-semibold tabular-nums text-destructive">−{exitsInRange.length}</p><p className="text-[10px] text-muted-foreground">Exited</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /><div><p className="text-2xl font-semibold tabular-nums">{closingHeadcount}</p><p className="text-[10px] text-muted-foreground">Closing</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4"><InsightItem label="ACTIVE TODAY" value={activeCount} /><InsightItem label="ANNUALISED ATTRITION" value={pct(attritionRate)} tone={attritionRate > 20 ? "warning" : "default"} /></div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Department concentration</CardTitle></CardHeader><CardContent className="space-y-3">{departmentInsights.length ? departmentInsights.map(row => <RankedBar key={row.name} label={row.name} value={row.gross} max={maxDepartmentGross} detail={`${row.active} active · ${pct(row.payrollShare)} of payroll`} />) : noData("No department mapping is available.")}</CardContent></Card></div>
      <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Employment mix</CardTitle></CardHeader><CardContent className="space-y-3">{employeeTypes.map((row, index) => <div key={row.name} className="flex items-center gap-3"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} /><span className="min-w-0 flex-1 truncate text-xs font-medium capitalize text-foreground">{row.name}</span><span className="text-xs tabular-nums text-muted-foreground">{row.count} · {pct(row.share)}</span></div>)}</CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm">Data readiness<UiTooltip><TooltipTrigger asChild><Info className="h-3.5 w-3.5 text-muted-foreground" /></TooltipTrigger><TooltipContent>Missing workforce fields reduce historical accuracy.</TooltipContent></UiTooltip></CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><InsightItem label="MISSING JOINING DATE" value={missingJoiningDates} note="Excluded from historical headcount" tone={missingJoiningDates ? "warning" : "default"} /><InsightItem label="UNMAPPED DEPARTMENT" value={unmappedDepartments} tone={unmappedDepartments ? "warning" : "default"} /></CardContent></Card></div>
    </section>

    <section className="space-y-3"><SectionHeader eyebrow="Leave & availability" title="Capacity impact" />
      <div className="grid gap-4 xl:grid-cols-3"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Leave position</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><InsightItem label="APPROVED DAYS" value={approvedLeaveDays.toLocaleString("en-IN")} note={`${leaveDaysPerEmployee.toFixed(1)} days per active employee`} /><InsightItem label="PENDING DECISIONS" value={pendingLeaves.length} tone={pendingLeaves.length ? "warning" : "default"} /><div className="col-span-2 border-t border-border pt-3"><p className="mb-2 text-[11px] font-semibold text-muted-foreground">APPROVED DAYS BY TYPE</p>{leaveByType.length ? <div className="space-y-2">{leaveByType.map(row => <div key={row.name} className="flex justify-between gap-3 text-xs"><span className="text-foreground">{row.name}</span><span className="font-semibold tabular-nums">{row.days.toLocaleString("en-IN")}</span></div>)}</div> : <p className="text-xs text-muted-foreground">No approved leave in this period.</p>}</div></CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Leave impact by department</CardTitle></CardHeader><CardContent className="space-y-3">{leaveByDepartment.length ? leaveByDepartment.map(row => <RankedBar key={row.name} label={row.name} value={row.days} max={maxLeaveDays} suffix=" days" />) : noData("No approved leave days in this period.")}</CardContent></Card>
        <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Workforce availability</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="text-3xl font-semibold tabular-nums text-foreground">{availabilityNow.marked ? pct(availabilityNow.rate) : "—"}</p><div className="mt-1 text-xs text-muted-foreground"><Delta value={availabilityDelta} /></div></div><div className="grid grid-cols-2 gap-3 border-t border-border pt-4"><InsightItem label="EQUIVALENT DAYS LOST" value={availabilityNow.lost.toLocaleString("en-IN")} /><InsightItem label="AVERAGE WORKDAY" value={`${availabilityNow.averageHours.toFixed(1)} h`} /></div></CardContent></Card></div>
    </section>

    <Card className="border-dashed"><CardContent className="flex items-start gap-3 p-4"><Landmark className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" /><div><p className="text-xs font-semibold text-foreground">Methodology</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Payroll uses the RazorpayX payslip mirror. Employer payroll cost = gross payroll + employer contributions. Headcount uses actual joining and exit dates. Leave counts approved days only. Availability uses evidence-backed attendance days. Owners/directors are excluded from every figure, drill-down and export.</p></div></CardContent></Card>

    <MonthlyPayrollBreakdownDialog monthKey={drillMonth} monthLabel={drillMonth ? monthLabel(drillMonth) : ""} onClose={() => setDrillMonth(null)} empName={empName} deptOf={deptOf} excludeEmployeeIds={excludedEmployeeIds} empBadge={id => (empById.get(id) as any)?.badge_id || "—"} />
  </div></TooltipProvider>;
}
