// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
function supabaseForUser(ctx) {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const anonKey = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients from the ERP client directory, most recently onboarded first. Respects the signed-in user's permissions (RLS).",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive filter on client name or phone."),
    limit: z.number().int().optional().describe("Max rows to return (default 25, capped at 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const cap = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("clients").select(
      "id, name, phone, client_type, risk_appetite, kyc_status, client_value_score, date_of_onboarding"
    ).eq("is_deleted", false).order("date_of_onboarding", { ascending: false }).limit(cap);
    if (search && search.trim())
      query = query.or(`name.ilike.%${search.trim()}%,phone.ilike.%${search.trim()}%`);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data }
    };
  }
});

// src/lib/mcp/tools/list-sales-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_sales_orders_default = defineTool2({
  name: "list_sales_orders",
  title: "List sales orders",
  description: "List recent sales orders from the ERP, newest first. Respects the signed-in user's permissions (RLS).",
  inputSchema: {
    status: z2.string().optional().describe("Optional exact status filter (e.g. completed, pending)."),
    limit: z2.number().int().optional().describe("Max rows to return (default 25, capped at 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const cap = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("sales_orders").select(
      "id, order_number, client_name, product_id, quantity, price_per_unit, total_amount, status, payment_status, order_date"
    ).order("order_date", { ascending: false }).limit(cap);
    if (status && status.trim()) query = query.eq("status", status.trim());
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sales_orders: data }
    };
  }
});

// src/lib/mcp/tools/list-purchase-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_purchase_orders_default = defineTool3({
  name: "list_purchase_orders",
  title: "List purchase orders",
  description: "List recent purchase orders from the ERP, newest first. Respects the signed-in user's permissions (RLS).",
  inputSchema: {
    status: z3.string().optional().describe("Optional exact status filter (e.g. completed, pending)."),
    limit: z3.number().int().optional().describe("Max rows to return (default 25, capped at 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const cap = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("purchase_orders").select(
      "id, order_number, supplier_name, product_name, quantity, price_per_unit, total_amount, status, order_date"
    ).order("order_date", { ascending: false }).limit(cap);
    if (status && status.trim()) query = query.eq("status", status.trim());
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { purchase_orders: data }
    };
  }
});

// src/lib/mcp/tools/get-wallet-balances.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_wallet_balances_default = defineTool4({
  name: "get_wallet_balances",
  title: "Get wallet balances",
  description: "Get current multi-asset wallet balances (USDT, TRX, BTC, etc.) from the ERP ledger. Respects the signed-in user's permissions (RLS).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("wallet_asset_balances").select("wallet_id, asset_code, balance, total_received, total_sent, updated_at").order("asset_code", { ascending: true });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { balances: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vagiqbespusdxsbqpvbo";
var mcp_default = defineMcp({
  name: "blynkex-erp-mcp",
  title: "Blynkex ERP MCP",
  version: "0.1.0",
  instructions: "Read-only access to the Blynkex ERP. Use list_clients, list_sales_orders, and list_purchase_orders to browse records, and get_wallet_balances for current multi-asset holdings. All access is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_sales_orders_default, list_purchase_orders_default, get_wallet_balances_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
