-- Drop the existing function first
DROP FUNCTION IF EXISTS generate_employee_id(text, text);

-- Add missing columns to employees table for comprehensive employee management
ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS middle_name text,
ADD COLUMN IF NOT EXISTS gender text CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
ADD COLUMN IF NOT EXISTS date_of_birth date,
ADD COLUMN IF NOT EXISTS blood_group text,
ADD COLUMN IF NOT EXISTS marital_status text CHECK (marital_status IN ('SINGLE', 'MARRIED', 'OTHER')),
ADD COLUMN IF NOT EXISTS alternate_phone text,
ADD COLUMN IF NOT EXISTS current_address text,
ADD COLUMN IF NOT EXISTS permanent_address text,
ADD COLUMN IF NOT EXISTS emergency_contact_name text,
ADD COLUMN IF NOT EXISTS emergency_contact_relation text,
ADD COLUMN IF NOT EXISTS emergency_contact_number text,
ADD COLUMN IF NOT EXISTS reporting_manager_id uuid REFERENCES employees(id),
ADD COLUMN IF NOT EXISTS work_location text CHECK (work_location IN ('OFFICE', 'REMOTE', 'HYBRID')),
ADD COLUMN IF NOT EXISTS employee_type text CHECK (employee_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'CONSULTANT')),
ADD COLUMN IF NOT EXISTS probation_period boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS probation_duration_months integer,
ADD COLUMN IF NOT EXISTS pan_number text,
ADD COLUMN IF NOT EXISTS aadhaar_number text,
ADD COLUMN IF NOT EXISTS bank_account_holder_name text,
ADD COLUMN IF NOT EXISTS bank_name text,
ADD COLUMN IF NOT EXISTS account_number text,
ADD COLUMN IF NOT EXISTS ifsc_code text,
ADD COLUMN IF NOT EXISTS upi_id text,
ADD COLUMN IF NOT EXISTS ctc numeric,
ADD COLUMN IF NOT EXISTS basic_salary numeric,
ADD COLUMN IF NOT EXISTS allowances numeric,
ADD COLUMN IF NOT EXISTS incentives numeric,
ADD COLUMN IF NOT EXISTS deductions numeric,
ADD COLUMN IF NOT EXISTS aadhaar_card_url text,
ADD COLUMN IF NOT EXISTS pan_card_url text,
ADD COLUMN IF NOT EXISTS photo_url text,
ADD COLUMN IF NOT EXISTS resume_url text,
ADD COLUMN IF NOT EXISTS offer_letter_url text,
ADD COLUMN IF NOT EXISTS other_certificates_urls text[],
ADD COLUMN IF NOT EXISTS nda_acknowledged boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS nda_acknowledged_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS handbook_acknowledged boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS handbook_acknowledged_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS kyc_status text DEFAULT 'PENDING' CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
ADD COLUMN IF NOT EXISTS approval_status text DEFAULT 'PENDING' CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
ADD COLUMN IF NOT EXISTS approved_by uuid,
ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS rejection_reason text;