-- Add specific fields for different case types
ALTER TABLE public.bank_cases 
ADD COLUMN error_message TEXT,
ADD COLUMN screenshots TEXT[],
ADD COLUMN wrong_beneficiary_account TEXT,
ADD COLUMN wrong_beneficiary_name TEXT,
ADD COLUMN transaction_datetime TIMESTAMP WITH TIME ZONE,
ADD COLUMN amount_transferred NUMERIC,
ADD COLUMN beneficiary_name TEXT,
ADD COLUMN beneficiary_account_number TEXT,
ADD COLUMN bank_ifsc_code TEXT,
ADD COLUMN proof_of_debit TEXT,
ADD COLUMN settlement_reference_id TEXT,
ADD COLUMN expected_settlement_amount NUMERIC,
ADD COLUMN settlement_date DATE,
ADD COLUMN pending_since TEXT,
ADD COLUMN supporting_proof TEXT,
ADD COLUMN amount_lien_marked NUMERIC,
ADD COLUMN date_lien_marked DATE,
ADD COLUMN bank_reason TEXT,
ADD COLUMN supporting_document TEXT,
ADD COLUMN remarks TEXT,
ADD COLUMN date_of_discrepancy DATE,
ADD COLUMN reported_balance NUMERIC,
ADD COLUMN expected_balance NUMERIC,
ADD COLUMN difference_amount NUMERIC,
ADD COLUMN statement_proof TEXT;