-- Backfill ERP tasks for 7 existing FAILED spot trades
INSERT INTO erp_tasks (title, description, priority, status, tags)
VALUES
  ('Spot Trade Failed: BTCUSDT SELL', 'Symbol: BTCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 0.01457978' || E'\n' || 'Error: Account has insufficient balance for requested action.' || E'\n' || 'Trade ID: b3658593-8785-4338-b130-66423e9c8a9d', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']),
  ('Spot Trade Failed: BTCUSDT SELL', 'Symbol: BTCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 0.01457978' || E'\n' || 'Error: Account has insufficient balance for requested action.' || E'\n' || 'Trade ID: e774f828-825d-4c8c-94dd-7ee5f0a41f34', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']),
  ('Spot Trade Failed: BTCUSDT SELL', 'Symbol: BTCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 0.00014418' || E'\n' || 'Error: Filter failure: LOT_SIZE' || E'\n' || 'Trade ID: b3df3648-e7b3-4066-8163-d62b5ec52713', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']),
  ('Spot Trade Failed: BTCUSDT SELL', 'Symbol: BTCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 0.00000012' || E'\n' || 'Error: Invalid quantity.' || E'\n' || 'Trade ID: 1bdb6c19-9f92-4deb-a906-c093b9ba1a04', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']),
  ('Spot Trade Failed: USDCUSDT SELL', 'Symbol: USDCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 250.79459765' || E'\n' || 'Error: Filter failure: LOT_SIZE' || E'\n' || 'Trade ID: 10b4fcd0-262d-4663-8511-ea6978e82a78', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']),
  ('Spot Trade Failed: USDCUSDT SELL', 'Symbol: USDCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 250.79459765' || E'\n' || 'Error: Filter failure: LOT_SIZE' || E'\n' || 'Trade ID: 97ef66b8-736a-431c-add3-7f78e13dbaaa', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']),
  ('Spot Trade Failed: USDCUSDT SELL', 'Symbol: USDCUSDT' || E'\n' || 'Side: SELL' || E'\n' || 'Quantity: 250.79459765' || E'\n' || 'Error: Filter failure: LOT_SIZE' || E'\n' || 'Trade ID: d17582b1-6acd-4f57-b3ae-7c3e070130b9', 'high', 'open', ARRAY['spot-trade', 'auto-generated', 'backfill']);