ALTER TABLE public.kb_documents
  ADD COLUMN IF NOT EXISTS ingest_stage TEXT,
  ADD COLUMN IF NOT EXISTS ingest_progress INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ingest_stage_detail TEXT,
  ADD COLUMN IF NOT EXISTS ingest_total_chunks INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ingest_done_chunks INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ingest_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ingest_updated_at TIMESTAMPTZ;